# PANEL-ONLY PRESENTATION COPY — generated by SUTRA_PANEL_ONLY_CANONICAL_V0_2
# Scientific calculations/data access are unchanged; only axes/figure titles and literal panel letters are suppressed.
"""Disease supplementary collective-organization panels from frozen Part-1 artifacts.
Never reruns the SUTRA hierarchy. Aggregation nulls are downstream controls only.
"""
from pathlib import Path
import argparse, json, hashlib
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import pyarrow.parquet as pq
from scipy.sparse import csc_matrix
import h5py
plt.rcParams.update({'font.family': 'Arial', 'font.size': 8, 'axes.linewidth': 0.75, 'pdf.fonttype': 42, 'ps.fonttype': 42})
DISPLAY = {'healthy_reference': 'Healthy brain', 'alzheimers': "Alzheimer's disease", 'gbm_reference_addon': 'GBM', 'nondiseased_kidney': 'Nondiseased kidney', 'prcc': 'PRCC'}
COMPS = {'hb-ad': ('healthy_reference', 'alzheimers', 'SuppFig03_HB_AD'), 'hb-gbm': ('healthy_reference', 'gbm_reference_addon', 'SuppFig04_HB_GBM'), 'nk-prcc': ('nondiseased_kidney', 'prcc', 'SuppFig05_NK_PRCC')}

def read_steps(d):
    with (d / 'steps.jsonl').open() as f:
        return [json.loads(x) for x in f if x.strip()]

def read_edges(d, k):
    p = d / 'merge_events' / f'step_{k:06d}.parquet'
    if not p.exists():
        return np.empty((0, 2), np.int64)
    q = pq.read_table(p, columns=['survivor_node', 'removed_node']).to_pandas().dropna()
    return q[['survivor_node', 'removed_node']].to_numpy(np.int64)

class DSU:

    def __init__(self, n):
        self.p = np.arange(n)
        self.sz = np.ones(n, np.int64)

    def find(self, a):
        while self.p[a] != a:
            self.p[a] = self.p[self.p[a]]
            a = int(self.p[a])
        return a

    def union(self, a, b):
        a = self.find(int(a))
        b = self.find(int(b))
        if a == b:
            return
        self.p[b] = a
        self.sz[a] += self.sz[b]
        self.sz[b] = 0

    def masses(self):
        return self.sz[(self.p == np.arange(len(self.p))) & (self.sz > 0)]

    def labels(self):
        return np.array([self.find(i) for i in range(len(self.p))], np.int64)

def phi(ds, n):
    return float(ds.masses().max() / n)

def audit_hierarchy_coordinate(d, steps, expected_n=None, atol=5e-12):
    """Validate the authoritative v0911 hierarchy coordinate without rerunning hierarchy.

 v0911 records hierarchy_coordinate_removed_fraction at entry to each microstep.
 Productive records additionally record removed_fraction_after and cumulative_merges_after.
 The terminal exhaustion record has selected_merges == 0 and therefore need not contain
 an after-state.
 """
    if not steps:
        raise RuntimeError(f'No hierarchy step records: {d}')
    n0 = int(steps[0]['level0_cells'])
    if expected_n is not None and int(expected_n) != n0:
        raise RuntimeError(f'level0_cells mismatch: flow_summary={expected_n}, ledger={n0}')
    previous_after = 0.0
    productive = 0
    for i, r in enumerate(steps):
        k = int(r['microstep'])
        for key in ('hierarchy_coordinate_removed_fraction', 'cumulative_merges', 'selected_merges', 'level0_cells'):
            if key not in r:
                raise RuntimeError(f'{d.name} microstep {k}: missing required v0911 field {key}')
        if int(r['level0_cells']) != n0:
            raise RuntimeError(f'{d.name} microstep {k}: level0_cells changed')
        u_before = float(r['hierarchy_coordinate_removed_fraction'])
        u_from_count = int(r['cumulative_merges']) / n0
        if not np.isclose(u_before, u_from_count, rtol=0, atol=atol):
            raise RuntimeError(f'{d.name} microstep {k}: entry-u mismatch: hierarchy={u_before}, cumulative/N0={u_from_count}')
        if i and (not np.isclose(u_before, previous_after, rtol=0, atol=atol)):
            raise RuntimeError(f'{d.name} microstep {k}: hierarchy coordinate is not continuous: {u_before} vs previous {previous_after}')
        nsel = int(r['selected_merges'])
        if nsel > 0:
            productive += 1
            for key in ('removed_fraction_after', 'cumulative_merges_after', 'nodes_after'):
                if key not in r:
                    raise RuntimeError(f'{d.name} productive microstep {k}: missing {key}')
            u_after = float(r['removed_fraction_after'])
            u_after_count = int(r['cumulative_merges_after']) / n0
            if not np.isclose(u_after, u_after_count, rtol=0, atol=atol):
                raise RuntimeError(f'{d.name} microstep {k}: post-u mismatch: removed_fraction_after={u_after}, cumulative_after/N0={u_after_count}')
            if int(r['cumulative_merges_after']) - int(r['cumulative_merges']) != nsel:
                raise RuntimeError(f'{d.name} microstep {k}: selected_merges inconsistent with cumulative counts')
            previous_after = u_after
        else:
            previous_after = u_before
    terminal = steps[-1]
    terminal_u = float(terminal['hierarchy_coordinate_removed_fraction'])
    terminal_count = int(terminal['cumulative_merges'])
    stop = terminal.get('stop_reason')
    if int(terminal.get('selected_merges', -1)) != 0:
        raise RuntimeError(f'{d.name}: final ledger record is not a zero-merger stopping record')
    if stop != 'no_contextually_admissible_boundaries':
        raise RuntimeError(f'{d.name}: unexpected terminal stop_reason={stop!r}')
    if not np.isclose(terminal_u, terminal_count / n0, rtol=0, atol=atol):
        raise RuntimeError(f'{d.name}: terminal-u mismatch')
    return {'sample': d.name, 'N0': n0, 'u_source': 'hierarchy_coordinate_removed_fraction (pre-step); removed_fraction_after (productive post-step)', 'productive_microsteps': productive, 'terminal_microstep': int(terminal['microstep']), 'terminal_merges': terminal_count, 'terminal_u': terminal_u, 'stop_reason': stop}

def reconstruct(root, sample):
    d = root / 'hierarchy_v0911_specimen_local_contextual_flow/ledger' / sample
    summ = json.loads((d / 'flow_summary.json').read_text())
    expected_n = summ.get('level0_cells', summ.get('N0', None))
    steps = read_steps(d)
    audit = audit_hierarchy_coordinate(d, steps, expected_n=expected_n)
    n = int(audit['N0'])
    ds = DSU(n)
    rows = []
    snaps = {0: np.ones(n, np.int64)}
    prev = 1 / n
    best = (-1, None)
    targets = [0.1, 0.25, 0.4, 0.55]
    ti = 0
    rows.append((0.0, 1 / n, 0.0, -1))
    for r in steps:
        k = int(r['microstep'])
        nsel = int(r['selected_merges'])
        if nsel <= 0:
            continue
        edges = read_edges(d, k)
        if len(edges) != nsel:
            raise RuntimeError(f'{sample} microstep {k}: ledger selected_merges={nsel}, merge-event rows={len(edges)}')
        for a, b in edges:
            if not (0 <= a < n and 0 <= b < n):
                raise RuntimeError(f'{sample} microstep {k}: node id outside [0,{n}) in merge ledger: {(int(a), int(b))}')
            ds.union(a, b)
        u = float(r['removed_fraction_after'])
        ph = phi(ds, n)
        delta = ph - prev
        rows.append((u, ph, delta, k))
        prev = ph
        if delta > best[0]:
            best = (delta, k)
        while ti < len(targets) and u >= targets[ti]:
            snaps[targets[ti]] = ds.masses().copy()
            ti += 1
    terminal_phi = phi(ds, n)
    if not np.isclose(rows[-1][0], audit['terminal_u'], rtol=0, atol=5e-12):
        raise RuntimeError(f"{sample}: reconstructed terminal u={rows[-1][0]} != audited terminal u={audit['terminal_u']}")
    snaps['terminal'] = ds.masses().copy()
    audit['terminal_phi'] = terminal_phi
    return (pd.DataFrame(rows, columns=['u', 'phi', 'delta_phi', 'microstep']), snaps, best[1], steps, n, d, audit)

def peak_members(d, steps, n, peak):
    ds = DSU(n)
    for r in steps:
        k = int(r['microstep'])
        if k == peak:
            pre = ds.labels()
            pre_mass = pd.Series(pre).value_counts()
            pre_root = int(pre_mass.index[0])
            pre_ids = np.flatnonzero(pre == pre_root)
            for a, b in read_edges(d, k):
                if 0 <= a < n and 0 <= b < n:
                    ds.union(a, b)
            post = ds.labels()
            post_mass = pd.Series(post).value_counts()
            post_root = int(post_mass.index[0])
            post_ids = np.flatnonzero(post == post_root)
            recruited = np.setdiff1d(post_ids, pre_ids)
            return (pre_ids, recruited, post_ids)
        for a, b in read_edges(d, k):
            if 0 <= a < n and 0 <= b < n:
                ds.union(a, b)
    raise RuntimeError('peak not found')

def aggregation_null(steps, n, uobs, reps, seed):
    productive = [r for r in steps if int(r.get('_nsel', 0)) > 0]
    grid = np.asarray(uobs, dtype=float)
    if len(grid) != len(productive) + 1:
        raise RuntimeError(f'null state-count mismatch: observed states={len(grid)}, productive steps={len(productive)}; expected states=productive+1')
    expected_merges = sum((int(r['_nsel']) for r in productive))
    expected_terminal_u = expected_merges / float(n)
    if not np.isclose(grid[-1], expected_terminal_u, rtol=0, atol=5e-12):
        raise RuntimeError(f'null terminal-u mismatch: trajectory u={grid[-1]}, productive merges/N0={expected_terminal_u}')
    print('=== aggregation-null bookkeeping audit ===')
    print(json.dumps({'N0': int(n), 'trajectory_states': int(len(grid)), 'productive_microsteps': int(len(productive)), 'accepted_merges': int(expected_merges), 'terminal_u': float(expected_terminal_u), 'null_reps': int(reps)}, indent=2))
    rng = np.random.default_rng(seed)
    vals = np.empty((reps, len(grid)), dtype=float)
    for rr in range(reps):
        ds = DSU(n)
        vals[rr, 0] = 1 / n
        realized = 0
        for j, r in enumerate(productive, 1):
            m = int(r['_nsel'])
            roots = np.flatnonzero((ds.p == np.arange(n)) & (ds.sz > 0))
            if 2 * m > len(roots):
                raise RuntimeError(f"null replicate {rr}: cannot realize {m} disjoint random pairings from {len(roots)} active objects at microstep {r.get('microstep')}")
            pick = rng.choice(roots, size=2 * m, replace=False)
            for z in range(m):
                ds.union(pick[2 * z], pick[2 * z + 1])
            realized += m
            vals[rr, j] = phi(ds, n)
        if realized != expected_merges:
            raise RuntimeError(f'null replicate {rr}: realized merges={realized}, expected={expected_merges}')
    return np.quantile(vals, [0.025, 0.5, 0.975], axis=0)

def prepare_steps(d, steps):
    out = []
    for r in steps:
        z = dict(r)
        ledger_nsel = int(r.get('selected_merges', 0))
        event_nsel = len(read_edges(d, int(r['microstep']))) if ledger_nsel > 0 else 0
        if event_nsel != ledger_nsel:
            raise RuntimeError(f"microstep {r['microstep']}: selected_merges={ledger_nsel}, merge-event rows={event_nsel}")
        z['_nsel'] = event_nsel
        out.append(z)
    return out

def feature_names(level0):
    f = pd.read_parquet(level0 / 'features.parquet')
    for c in ['feature_name', 'gene_name', 'name', 'feature_id']:
        if c in f.columns:
            return f[c].astype(str).to_numpy()
    raise RuntimeError('No feature-name column')

def matrix(level0):
    man = json.loads((level0 / 'expression_manifest.json').read_text())
    p = Path(man['source_matrix'])
    if not p.exists():
        raise FileNotFoundError(f'Expression source missing: {p}')
    with h5py.File(p, 'r') as h:
        g = h['matrix']
        shape = tuple(g['shape'][()])
        X = csc_matrix((g['data'][()], g['indices'][()], g['indptr'][()]), shape=shape)
    return X

def molecular(level0, pre, recr, common=None, top=12):
    X = matrix(level0)
    names = feature_names(level0)
    cells = pd.read_parquet(level0 / 'cells.parquet')
    cols = cells['matrix_column'].to_numpy(int) if 'matrix_column' in cells.columns else np.arange(len(cells))

    def avg(ids):
        C = cols[np.asarray(ids, int)]
        sub = X[:, C].astype(float)
        lib = np.asarray(sub.sum(axis=0)).ravel()
        lib[lib <= 0] = 1
        sub = sub @ __import__('scipy').sparse.diags(10000.0 / lib)
        return np.asarray(np.log1p(sub).mean(axis=1)).ravel()
    a, b = (avg(pre), avg(recr))
    eff = b - a
    keep = np.ones(len(names), bool) if common is None else np.isin(names, common)
    idx = np.flatnonzero(keep)
    idx = idx[np.argsort(np.abs(eff[idx]))[-top:]]
    idx = idx[np.argsort(eff[idx])]
    return pd.DataFrame({'gene': names[idx], 'effect_log1p_norm': eff[idx]})

def overlap(level0a, level0b):
    a = feature_names(level0a)
    b = feature_names(level0b)
    common = np.intersect1d(a, b)
    return (a, b, common)

def save(fig, out, stem):
    fig.savefig(out / (stem + '.png'), dpi=600, bbox_inches='tight', facecolor='white')
    fig.savefig(out / (stem + '.pdf'), bbox_inches='tight', facecolor='white')
    plt.close(fig)

def pmf(ax, m, title):
    m = np.asarray(m)
    m = m[m >= 2]
    v, c = np.unique(m, return_counts=True)
    p = c / c.sum()
    ax.scatter(v, p, s=8, alpha=0.8)
    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_xlabel('Object mass, m')
    ax.set_ylabel('P(m | m ≥ 2)')
    pass
    ax.spines[['top', 'right']].set_visible(False)

def spatial(ax, level0, pre, recr, title):
    c = pd.read_parquet(level0 / 'cells.parquet')
    x = next((z for z in ['x', 'x_centroid', 'centroid_x'] if z in c.columns))
    y = next((z for z in ['y', 'y_centroid', 'centroid_y'] if z in c.columns))
    ax.scatter(c[x], c[y], s=0.15, c='.88', linewidths=0, rasterized=True)
    ax.scatter(c.iloc[pre][x], c.iloc[pre][y], s=0.4, c='0.25', linewidths=0, rasterized=True, label='pre-event M1')
    ax.scatter(c.iloc[recr][x], c.iloc[recr][y], s=0.7, c='tab:orange', linewidths=0, rasterized=True, label='recruited')
    ax.set_aspect('equal')
    ax.set_xticks([])
    ax.set_yticks([])
    pass
    ax.legend(frameon=False, fontsize=6, markerscale=4)
    [s.set_visible(False) for s in ax.spines.values()]

def run(args):
    mr = Path(args.main_results).expanduser().resolve()
    ref, dis, folder = COMPS[args.comparison]
    out = Path(args.output_root).expanduser().resolve() / 'supplementary' / folder
    out.mkdir(parents=True, exist_ok=True)
    L = mr / 'hierarchy_level0_v070'
    led = mr / 'hierarchy_v0911_specimen_local_contextual_flow/ledger'
    A, B, common = overlap(L / ref, L / dis)
    audit = {'comparison': args.comparison, 'reference': ref, 'comparison_sample': dis, 'reference_features': len(A), 'comparison_features': len(B), 'common_features': len(common), 'reference_only': len(np.setdiff1d(A, B)), 'comparison_only': len(np.setdiff1d(B, A)), 'common_fraction_reference': len(common) / len(A), 'common_fraction_comparison': len(common) / len(B)}
    (out / 'panel_overlap_audit.json').write_text(json.dumps(audit, indent=2))
    pd.DataFrame({'gene': common}).to_csv(out / 'common_gene_basis.csv', index=False)
    if args.comparison == 'hb-ad' and len(common) != 451:
        raise RuntimeError(f'HB-AD common panel expected 451, observed {len(common)}')
    if args.comparison == 'nk-prcc' and len(common) != 541:
        raise RuntimeError(f'NK-PRCC common panel expected 541, observed {len(common)}')
    if args.check_only:
        print(json.dumps(audit, indent=2))
        return
    R = {}
    for si, s in enumerate([ref, dis]):
        tr, sn, pk, steps, n, d, ha = reconstruct(mr, s)
        print('=== hierarchy-coordinate audit ===')
        print(json.dumps(ha, indent=2))
        (out / f'{s}_hierarchy_coordinate_audit.json').write_text(json.dumps(ha, indent=2))
        steps2 = prepare_steps(d, steps)
        q = aggregation_null(steps2, n, tr.u.to_numpy(), args.null_reps, args.seed + si)
        pre, recr, post = peak_members(d, steps, n, pk)
        mol = molecular(L / s, pre, recr, common=common)
        R[s] = (tr, sn, pk, q, pre, recr, mol)
        tr.to_csv(out / f'{s}_collective_trajectory.csv', index=False)
        mol.to_csv(out / f'{s}_molecular_recruitment.csv', index=False)
        pd.DataFrame({'level0_index': recr}).to_csv(out / f'{s}_dominant_recruited_ids.csv', index=False)
    for letter, s in [('A', ref), ('B', dis)]:
        fig, ax = plt.subplots(figsize=(3.8, 3.2))
        pmf(ax, R[s][1]['terminal'], DISPLAY[s])
        fig.text(0.01, 0.98, letter, fontsize=17, fontweight='bold', va='top')
        save(fig, out, f'{letter}_{s}_collective_mass')
    for letter, s in [('C', ref), ('D', dis)]:
        tr, sn, pk, q, *_ = R[s]
        fig, ax = plt.subplots(figsize=(4.2, 3.2))
        ax.fill_between(tr.u, q[0], q[2], color='.85', label='aggregation-only null 95%')
        ax.plot(tr.u, q[1], color='.45', lw=1, label='null median')
        ax.plot(tr.u, tr.phi, color='black', lw=1.4, label='observed')
        ax.set_xlabel('Removed fraction, u')
        ax.set_ylabel('Largest-object fraction, Φ(u)')
        pass
        ax.legend(frameon=False, fontsize=6)
        ax.spines[['top', 'right']].set_visible(False)
        fig.text(0.01, 0.98, letter, fontsize=17, fontweight='bold', va='top')
        save(fig, out, f'{letter}_{s}_collective_reorganization')
    fig, axs = plt.subplots(1, 2, figsize=(8.4, 3.4), constrained_layout=True)
    for ax, s in zip(axs, [ref, dis]):
        spatial(ax, L / s, R[s][4], R[s][5], DISPLAY[s])
    pass
    save(fig, out, 'E_dominant_recruitment_spatial')
    fig, axs = plt.subplots(1, 2, figsize=(8.4, 3.6), constrained_layout=True)
    for ax, s in zip(axs, [ref, dis]):
        m = R[s][6]
        ax.barh(m.gene, m.effect_log1p_norm)
        ax.axvline(0, color='0.3', lw=0.7)
        ax.set_xlabel('Recruited − pre-event M1\nmean log1p normalized expression')
        pass
        ax.spines[['top', 'right']].set_visible(False)
    pass
    save(fig, out, 'F_molecular_recruitment')
    prov = {'figure_family': 'disease collective organization', 'comparison': args.comparison, 'hierarchy_source': str(led), 'hierarchy_rerun': False, 'aggregation_null': {'reps': args.null_reps, 'seed': args.seed, 'preserves': 'N0 and empirical number of accepted merges per microstep; randomizes active-object pairing'}, 'molecular_basis': 'exact feature-name intersection; missing genes never encoded as zero', 'panel_overlap': audit}
    (out / 'provenance.json').write_text(json.dumps(prov, indent=2))
    print('WROTE', out)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--main-results', required=True)
    ap.add_argument('--output-root', required=True)
    ap.add_argument('--comparison', choices=COMPS, required=True)
    ap.add_argument('--null-reps', type=int, default=250)
    ap.add_argument('--seed', type=int, default=20260922)
    ap.add_argument('--check-only', action='store_true')
    run(ap.parse_args())
if __name__ == '__main__':
    main()
