# PANEL-ONLY PRESENTATION COPY — generated by SUTRA_PANEL_ONLY_CANONICAL_V0_2
# Scientific calculations/data access are unchanged; only axes/figure titles and literal panel letters are suppressed.
from __future__ import annotations
import argparse
import json
import math
import re
import time
from pathlib import Path
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
from matplotlib.colors import hsv_to_rgb
ROOT = Path.home() / 'Desktop' / 'SUTRA'
SAMPLE = 'healthy_reference'
N0 = 24406
NF = 10681
FINAL_REMOVED = N0 - NF
LEDGER = ROOT / 'results' / 'hierarchy_v0911_specimen_local_contextual_flow' / 'ledger' / SAMPLE
LABEL_DIR = LEDGER / 'label_checkpoints'
MERGE_DIR = LEDGER / 'merge_events'
CAND_DIR = LEDGER / 'candidate_boundaries'
CELL_FILE = ROOT / 'data' / SAMPLE / 'cells.parquet'
BOUNDARY_FILE = ROOT / 'data' / SAMPLE / 'cell_boundaries.parquet'
FLOW_SUMMARY = LEDGER / 'flow_summary.json'
FIGROOT = ROOT / 'figures' / 'fig2'
PANELDIR = FIGROOT / 'panels'
SOURCEDIR = FIGROOT / 'source_data'
PANELDIR.mkdir(parents=True, exist_ok=True)
SOURCEDIR.mkdir(parents=True, exist_ok=True)
plt.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 8, 'axes.labelweight': 'bold', 'axes.titleweight': 'bold', 'pdf.fonttype': 42, 'ps.fonttype': 42})

def retry_read_parquet(path: Path, columns, attempts: int=8):
    last = None
    for attempt in range(1, attempts + 1):
        try:
            return pq.read_table(path, columns=columns)
        except (TimeoutError, OSError) as exc:
            last = exc
            if attempt == attempts:
                break
            wait_s = min(3 * attempt, 20)
            print(f'[I/O retry {attempt}/{attempts}] {path.name}; sleep {wait_s}s')
            time.sleep(wait_s)
    raise RuntimeError(f'Could not read {path}') from last

def step_from_name(path: Path) -> int:
    m = re.search('(\\d+)', path.stem)
    if not m:
        raise ValueError(path)
    return int(m.group(1))

def hierarchy_u(nodes: float) -> float:
    return float(np.clip((N0 - nodes) / max(FINAL_REMOVED, 1), 0, 1))

def deterministic_color(label: int):
    phi = 0.6180339887498949
    h = int(label) * phi % 1.0
    s = 0.72
    v = 0.92
    return hsv_to_rgb([h, s, v])

def save_panel(fig, letter: str):
    png = PANELDIR / f'panel_{letter}.png'
    pdf = PANELDIR / f'panel_{letter}.pdf'
    fig.savefig(png, dpi=600, bbox_inches='tight', pad_inches=0.025, facecolor='white')
    fig.savefig(pdf, bbox_inches='tight', pad_inches=0.025, facecolor='white')
    plt.close(fig)
    print(f'panel {letter}:', png)

def merge_trajectory():
    files = sorted(MERGE_DIR.glob('step_*.parquet'), key=step_from_name)
    if not files:
        raise RuntimeError('No merge-event files')
    rows = []
    nodes = N0
    cumulative = 0
    rows.append({'step': 0, 'nodes': nodes, 'merges_this_step': 0, 'cumulative_merges': cumulative, 'removed_fraction': 0.0, 'u': 0.0, 'mean_mass': 1.0})
    for p in files:
        step = step_from_name(p)
        pf = pq.ParquetFile(p)
        nm = int(pf.metadata.num_rows)
        cumulative += nm
        nodes -= nm
        rows.append({'step': step + 1, 'nodes': nodes, 'merges_this_step': nm, 'cumulative_merges': cumulative, 'removed_fraction': (N0 - nodes) / N0, 'u': hierarchy_u(nodes), 'mean_mass': N0 / nodes})
    df = pd.DataFrame(rows)
    final = df.iloc[-1]
    print()
    print('TRAJECTORY')
    print('initial:', N0, 'final:', int(final.nodes), 'merges:', int(final.cumulative_merges))
    if int(final.nodes) != NF:
        raise RuntimeError(f'trajectory final nodes {int(final.nodes)} != {NF}')
    df.to_csv(SOURCEDIR / 'hierarchy_trajectory.csv', index=False)
    return df

def load_label_checkpoints():
    files = sorted(LABEL_DIR.glob('labels_*.npz'), key=step_from_name)
    rows = []
    arrays = {}
    for p in files:
        step = step_from_name(p)
        with np.load(p, allow_pickle=False) as z:
            labels = np.asarray(z['labels'], dtype=np.int64)
        if len(labels) != N0:
            raise RuntimeError(f'{p}: unexpected labels length')
        nodes = int(len(np.unique(labels)))
        arrays[step] = labels
        rows.append({'step': step, 'nodes': nodes, 'u': hierarchy_u(nodes), 'mean_mass': N0 / nodes})
    meta = pd.DataFrame(rows)
    meta.to_csv(SOURCEDIR / 'label_checkpoint_summary.csv', index=False)
    return (meta, arrays)

def choose_checkpoint_states(meta: pd.DataFrame, targets=(0.0, 1 / 3, 2 / 3, 1.0)):
    picked = []
    for target in targets:
        row = meta.iloc[np.argmin(np.abs(meta['u'].to_numpy() - target))]
        picked.append(row)
    return pd.DataFrame(picked).reset_index(drop=True)

def load_polygons():
    cells = retry_read_parquet(CELL_FILE, ['cell_id', 'x_centroid', 'y_centroid']).to_pandas()
    boundaries = retry_read_parquet(BOUNDARY_FILE, ['cell_id', 'vertex_x', 'vertex_y']).to_pandas()
    ids = cells['cell_id'].tolist()
    by_id = {}
    for cid, g in boundaries.groupby('cell_id', sort=False):
        poly = g[['vertex_x', 'vertex_y']].to_numpy(dtype=float)
        if len(poly) >= 3:
            by_id[cid] = poly
    polygons = []
    valid_indices = []
    for i, cid in enumerate(ids):
        if cid in by_id:
            polygons.append(by_id[cid])
            valid_indices.append(i)
    return (cells, polygons, np.asarray(valid_indices, dtype=int))

def panel_A(checkpoint_meta, checkpoint_arrays):
    cells, polygons, poly_idx = load_polygons()
    picked = choose_checkpoint_states(checkpoint_meta)
    picked.to_csv(SOURCEDIR / 'panel_A_states.csv', index=False)
    all_xy = np.vstack(polygons)
    xmin = all_xy[:, 0].min()
    xmax = all_xy[:, 0].max()
    ymin = all_xy[:, 1].min()
    ymax = all_xy[:, 1].max()
    fig, axes = plt.subplots(1, 4, figsize=(12.8, 3.3), facecolor='white')
    for ax, row in zip(axes, picked.itertuples()):
        step = int(row.step)
        labels = checkpoint_arrays[step]
        colors = np.asarray([deterministic_color(labels[i]) for i in poly_idx])
        pc = PolyCollection(polygons, facecolors=colors, edgecolors='white', linewidths=0.16)
        ax.add_collection(pc)
        ax.set_xlim(xmin, xmax)
        ax.set_ylim(ymin, ymax)
        ax.set_aspect('equal')
        ax.set_axis_off()
        if row.u <= 0.01:
            state_label = 'Level 0'
        elif row.u >= 0.99:
            state_label = 'Terminal'
        else:
            state_label = f'u = {row.u:.2f}'
        ax.text(0.5, 1.015, state_label, transform=ax.transAxes, ha='center', va='bottom', fontsize=8.3, weight='bold')
        ax.text(0.5, -0.015, f'{int(row.nodes):,} units', transform=ax.transAxes, ha='center', va='top', fontsize=7.3, weight='bold')
    fig.subplots_adjust(left=0.01, right=0.99, top=0.91, bottom=0.09, wspace=0.035)
    save_panel(fig, 'A')

def panel_B(traj):
    fig, ax = plt.subplots(figsize=(6.4, 3.5), facecolor='white')
    u = traj['u'].to_numpy()
    nodes = traj['nodes'].to_numpy()
    reduction = 1 - nodes / N0
    ax.plot(u, nodes, linewidth=2.0, color='0.15')
    ax.scatter([0, 1], [N0, NF], s=35, color='0.15', zorder=4)
    ax.set_xlim(0, 1)
    ax.set_xlabel('Normalized hierarchy progress, u')
    ax.set_ylabel('Active tissue units')
    ax.grid(alpha=0.14, linewidth=0.6)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax2 = ax.twinx()
    ax2.plot(u, 100 * reduction, linewidth=1.6, alpha=0.65, color='#555555', linestyle='--')
    ax2.set_ylabel('Node-count reduction (%)')
    ax2.set_ylim(0, max(60, 100 * reduction.max() * 1.08))
    ax2.spines['top'].set_visible(False)
    ax.text(0.02, 0.08, f'{N0:,}', transform=ax.transAxes, fontsize=7.5, weight='bold')
    ax.text(0.98, 0.08, f'{NF:,}', transform=ax.transAxes, ha='right', fontsize=7.5, weight='bold')
    fig.tight_layout(pad=0.7)
    save_panel(fig, 'B')

def panel_C(checkpoint_meta, checkpoint_arrays):
    records = []
    for row in checkpoint_meta.itertuples():
        step = int(row.step)
        labels = checkpoint_arrays[step]
        _, counts = np.unique(labels, return_counts=True)
        for q in [0.5, 0.9, 0.99]:
            records.append({'step': step, 'u': row.u, 'stat': f'q{int(100 * q)}', 'mass': float(np.quantile(counts, q))})
        records.append({'step': step, 'u': row.u, 'stat': 'max', 'mass': float(np.max(counts))})
    df = pd.DataFrame(records)
    df.to_csv(SOURCEDIR / 'panel_C_mass_quantiles.csv', index=False)
    fig, ax = plt.subplots(figsize=(6.2, 3.5), facecolor='white')
    styles = {'q50': ('Median', 1.6, '-'), 'q90': ('90th percentile', 1.7, '-'), 'q99': ('99th percentile', 1.8, '-'), 'max': ('Maximum', 2.0, '--')}
    for stat, (label, lw, ls) in styles.items():
        g = df[df.stat == stat]
        ax.plot(g.u, g.mass, label=label, linewidth=lw, linestyle=ls)
    ax.set_yscale('log')
    ax.set_xlim(0, 1)
    ax.set_xlabel('Normalized hierarchy progress, u')
    ax.set_ylabel('Supernode mass (Level-0 cells)')
    ax.grid(alpha=0.14, linewidth=0.6, which='both')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.legend(frameon=False, fontsize=7, ncol=2, loc='upper left')
    fig.tight_layout(pad=0.7)
    save_panel(fig, 'C')

def panel_D(traj):
    mean_mass = traj['mean_mass'].to_numpy()
    hops = np.minimum(8, 2 + np.floor(np.log2(np.maximum(mean_mass, 1.0))).astype(int))
    df = traj[['step', 'u', 'nodes', 'mean_mass']].copy()
    df['context_hops'] = hops
    df.to_csv(SOURCEDIR / 'panel_D_context_hops.csv', index=False)
    fig, ax = plt.subplots(figsize=(5.7, 3.5), facecolor='white')
    ax.step(df.u, df.context_hops, where='post', linewidth=2.2, color='#404040')
    ax.set_xlim(0, 1)
    ax.set_ylim(1.6, 8.4)
    ax.set_yticks(range(2, 9))
    ax.set_xlabel('Normalized hierarchy progress, u')
    ax.set_ylabel('Context radius (graph hops)')
    ax.grid(alpha=0.14, linewidth=0.6)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    seen = set()
    for row in df.itertuples():
        h = int(row.context_hops)
        if h in seen:
            continue
        seen.add(h)
        ax.scatter(row.u, h, s=24, color='#404040', zorder=4)
        ax.annotate(f'm̄≈{row.mean_mass:.2f}', (row.u, h), xytext=(4, 5), textcoords='offset points', fontsize=6.2)
    fig.tight_layout(pad=0.7)
    save_panel(fig, 'D')

def candidate_files():
    files = sorted(CAND_DIR.glob('step_*.parquet'), key=step_from_name)
    if not files:
        raise RuntimeError('No candidate-boundary files')
    return files

def select_candidate_files(files, n=45):
    if len(files) <= n:
        return files
    idx = np.unique(np.round(np.linspace(0, len(files) - 1, n)).astype(int))
    return [files[i] for i in idx]

def nodes_at_step(traj, step):
    x = traj[traj.step <= step]
    if len(x) == 0:
        return N0
    return int(x.iloc[-1].nodes)

def panel_E(traj):
    files = select_candidate_files(candidate_files(), n=45)
    rows = []
    for k, p in enumerate(files):
        step = step_from_name(p)
        tab = retry_read_parquet(p, ['composite_merge_cost', 'merge_cost_threshold'])
        cost = tab['composite_merge_cost'].to_numpy(zero_copy_only=False).astype(float)
        tau = tab['merge_cost_threshold'].to_numpy(zero_copy_only=False).astype(float)
        cost = cost[np.isfinite(cost)]
        tau = tau[np.isfinite(tau)]
        if not len(cost):
            continue
        nodes = nodes_at_step(traj, step)
        rows.append({'step': step, 'u': hierarchy_u(nodes), 'nodes': nodes, 'q10': float(np.quantile(cost, 0.1)), 'q25': float(np.quantile(cost, 0.25)), 'median': float(np.quantile(cost, 0.5)), 'q75': float(np.quantile(cost, 0.75)), 'q90': float(np.quantile(cost, 0.9)), 'threshold': float(np.median(tau)) if len(tau) else np.nan, 'candidate_count': int(len(cost))})
        print(f'E {k + 1:2d}/{len(files)} step={step}')
    df = pd.DataFrame(rows).sort_values('u')
    df.to_csv(SOURCEDIR / 'panel_E_cost_landscape.csv', index=False)
    fig, ax = plt.subplots(figsize=(6.2, 3.5), facecolor='white')
    ax.fill_between(df.u, df.q10, df.q90, alpha=0.1, label='10–90%')
    ax.fill_between(df.u, df.q25, df.q75, alpha=0.2, label='IQR')
    ax.plot(df.u, df['median'], linewidth=1.7, label='Candidate median')
    ax.plot(df.u, df.threshold, linewidth=2.1, linestyle='--', color='0.15', label='Admissibility threshold')
    positive = np.concatenate([df.q10.to_numpy(), df.q90.to_numpy(), df.threshold.to_numpy()])
    positive = positive[np.isfinite(positive) & (positive > 0)]
    if len(positive):
        ratio = positive.max() / positive.min()
        if ratio > 30:
            ax.set_yscale('log')
    ax.set_xlim(0, 1)
    ax.set_xlabel('Normalized hierarchy progress, u')
    ax.set_ylabel('Composite merge cost')
    ax.grid(alpha=0.14, linewidth=0.6, which='both')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.legend(frameon=False, fontsize=6.8, ncol=2)
    fig.tight_layout(pad=0.7)
    save_panel(fig, 'E')

def panel_F(traj):
    files = select_candidate_files(candidate_files(), n=65)
    rows = []
    for k, p in enumerate(files):
        step = step_from_name(p)
        pf = pq.ParquetFile(p)
        n_candidates = int(pf.metadata.num_rows)
        tab = retry_read_parquet(p, ['admissible'])
        adm = tab['admissible'].to_numpy(zero_copy_only=False)
        n_admissible = int(np.sum(adm.astype(bool)))
        nodes = nodes_at_step(traj, step)
        rows.append({'step': step, 'u': hierarchy_u(nodes), 'nodes': nodes, 'candidate_interfaces': n_candidates, 'admissible_interfaces': n_admissible, 'admissible_fraction': n_admissible / n_candidates if n_candidates else np.nan})
        print(f'F {k + 1:2d}/{len(files)} step={step} cand={n_candidates} adm={n_admissible}')
    df = pd.DataFrame(rows).sort_values('u')
    df.to_csv(SOURCEDIR / 'panel_F_interface_counts.csv', index=False)
    fig, ax = plt.subplots(figsize=(6.2, 3.5), facecolor='white')
    ax.plot(df.u, df.candidate_interfaces, linewidth=2.0, label='Candidate interfaces')
    ax.plot(df.u, df.admissible_interfaces, linewidth=2.0, label='Admissible interfaces')
    ax.set_xlim(0, 1)
    ax.set_ylim(bottom=0)
    ax.set_xlabel('Normalized hierarchy progress, u')
    ax.set_ylabel('Interface count')
    ax.grid(alpha=0.14, linewidth=0.6)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.legend(frameon=False, fontsize=7)
    last = df.iloc[-1]
    if int(last.admissible_interfaces) == 0:
        ax.scatter(last.u, last.candidate_interfaces, s=30, zorder=4)
        ax.scatter(last.u, 0, s=30, zorder=4)
        ax.annotate('candidate interfaces remain\nadmissible interfaces = 0', (last.u, 0), xytext=(-8, 25), textcoords='offset points', ha='right', fontsize=6.7, weight='bold')
    fig.tight_layout(pad=0.7)
    save_panel(fig, 'F')

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--panel', default='ALL', choices=['ALL', 'A', 'B', 'C', 'D', 'E', 'F'])
    args = parser.parse_args()
    traj = merge_trajectory()
    need_labels = args.panel in {'ALL', 'A', 'C'}
    if need_labels:
        meta, arrays = load_label_checkpoints()
    else:
        meta = None
        arrays = None
    jobs = ['A', 'B', 'C', 'D', 'E', 'F'] if args.panel == 'ALL' else [args.panel]
    for letter in jobs:
        print()
        print('=' * 72)
        print(f'FIGURE 2 PANEL {letter}')
        print('=' * 72)
        if letter == 'A':
            panel_A(meta, arrays)
        elif letter == 'B':
            panel_B(traj)
        elif letter == 'C':
            panel_C(meta, arrays)
        elif letter == 'D':
            panel_D(traj)
        elif letter == 'E':
            panel_E(traj)
        elif letter == 'F':
            panel_F(traj)
if __name__ == '__main__':
    main()
