# PANEL-ONLY PRESENTATION COPY — generated by SUTRA_PANEL_ONLY_CANONICAL_V0_2
# Scientific calculations/data access are unchanged; only axes/figure titles and literal panel letters are suppressed.
from pathlib import Path
import json
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
from matplotlib.colors import hsv_to_rgb
ROOT = Path.home() / 'Desktop' / 'SUTRA'
SAMPLE = 'healthy_reference'
BOUNDARY_FILE = ROOT / 'data' / SAMPLE / 'cell_boundaries.parquet'
CELL_FILE = ROOT / 'data' / SAMPLE / 'cells.parquet'
FIGROOT = ROOT / 'figures' / 'fig1'
PANELDIR = FIGROOT / 'panels'
SOURCEDIR = FIGROOT / 'source_data'
PANELDIR.mkdir(parents=True, exist_ok=True)
SOURCEDIR.mkdir(parents=True, exist_ok=True)
OUT_PDF = PANELDIR / 'panel_A.pdf'
OUT_PNG = PANELDIR / 'panel_A.png'
CROP_JSON = SOURCEDIR / 'panel_A_crop.json'
plt.rcParams.update({'font.family': 'Arial', 'font.size': 8, 'axes.linewidth': 0.7, 'pdf.fonttype': 42, 'ps.fonttype': 42, 'svg.fonttype': 'none'})

def choose_column(columns, candidates, purpose):
    lookup = {c.lower(): c for c in columns}
    for wanted in candidates:
        if wanted.lower() in lookup:
            return lookup[wanted.lower()]
    raise RuntimeError(f'Could not determine {purpose} column.\nAvailable columns:\n{columns}')
schema = pq.ParquetFile(BOUNDARY_FILE).schema_arrow
cols = schema.names
CELL_ID = choose_column(cols, ['cell_id', 'cell', 'cell_index', 'object_id', 'label'], 'cell identifier')
XCOL = choose_column(cols, ['vertex_x', 'x', 'x_location', 'x_coord', 'x_coordinate', 'boundary_x'], 'boundary x-coordinate')
YCOL = choose_column(cols, ['vertex_y', 'y', 'y_location', 'y_coord', 'y_coordinate', 'boundary_y'], 'boundary y-coordinate')
print('Boundary columns:')
print('  cell ID:', CELL_ID)
print('  x:', XCOL)
print('  y:', YCOL)
bd = pq.read_table(BOUNDARY_FILE, columns=[CELL_ID, XCOL, YCOL]).to_pandas()
bd = bd.dropna(subset=[CELL_ID, XCOL, YCOL])
bd[XCOL] = pd.to_numeric(bd[XCOL], errors='coerce')
bd[YCOL] = pd.to_numeric(bd[YCOL], errors='coerce')
bd = bd.dropna(subset=[XCOL, YCOL])
polygons = []
cell_ids = []
for cid, g in bd.groupby(CELL_ID, sort=False):
    xy = g[[XCOL, YCOL]].to_numpy(dtype=float)
    if len(xy) < 3:
        continue
    keep = np.ones(len(xy), dtype=bool)
    if len(xy) > 1:
        keep[1:] = np.any(np.diff(xy, axis=0) != 0, axis=1)
    xy = xy[keep]
    if len(xy) < 3:
        continue
    polygons.append(xy)
    cell_ids.append(cid)
print(f'Valid polygons: {len(polygons):,}')
centroids = np.array([np.mean(poly, axis=0) for poly in polygons])
cx = centroids[:, 0]
cy = centroids[:, 1]
qx1, qx2 = np.quantile(cx, [0.15, 0.85])
qy1, qy2 = np.quantile(cy, [0.15, 0.85])
central = (cx >= qx1) & (cx <= qx2) & (cy >= qy1) & (cy <= qy2)
central_centroids = centroids[central]
if len(central_centroids) < 100:
    raise RuntimeError('Could not identify a sufficiently populated central region.')
span_x = qx2 - qx1
span_y = qy2 - qy1
crop_w = 0.28 * span_x
crop_h = 0.28 * span_y
gx = np.linspace(qx1 + crop_w / 2, qx2 - crop_w / 2, 16)
gy = np.linspace(qy1 + crop_h / 2, qy2 - crop_h / 2, 16)
best = None
for x0 in gx:
    for y0 in gy:
        inside = (cx >= x0 - crop_w / 2) & (cx <= x0 + crop_w / 2) & (cy >= y0 - crop_h / 2) & (cy <= y0 + crop_h / 2)
        n = int(inside.sum())
        if best is None or n > best[0]:
            best = (n, x0, y0, inside)
n_crop, crop_cx, crop_cy, crop_mask = best
print(f'Cells in selected crop: {n_crop:,}')
xmin = crop_cx - crop_w / 2
xmax = crop_cx + crop_w / 2
ymin = crop_cy - crop_h / 2
ymax = crop_cy + crop_h / 2
crop_info = {'sample': SAMPLE, 'xmin': float(xmin), 'xmax': float(xmax), 'ymin': float(ymin), 'ymax': float(ymax), 'n_cells_intersecting_centroid_crop': int(n_crop), 'boundary_file': str(BOUNDARY_FILE)}
CROP_JSON.write_text(json.dumps(crop_info, indent=2) + '\n')
print('Saved crop:')
print(CROP_JSON)
crop_indices_poly = np.where(crop_mask)[0]
crop_polygons = [polygons[i] for i in crop_indices_poly]
golden = 0.6180339887498949
h = crop_indices_poly * golden % 1.0
saturation = 0.7 + 0.18 * (0.5 + 0.5 * np.sin(crop_indices_poly * 0.71))
value = 0.88 + 0.1 * (0.5 + 0.5 * np.cos(crop_indices_poly * 0.43))
crop_colors = hsv_to_rgb(np.column_stack([h, saturation, value]))
fig, ax = plt.subplots(figsize=(5.6, 5.2))
collection = PolyCollection(crop_polygons, facecolors=crop_colors, edgecolors='white', linewidths=0.2, antialiased=True)
ax.add_collection(collection)
ax.set_xlim(xmin, xmax)
ax.set_ylim(ymin, ymax)
ax.set_aspect('equal')
ax.set_xticks([])
ax.set_yticks([])
for spine in ax.spines.values():
    spine.set_visible(False)
width = xmax - xmin
candidate_lengths = np.array([10, 20, 25, 50, 100, 200, 250, 500, 1000], dtype=float)
target = 0.18 * width
bar_length = candidate_lengths[np.argmin(np.abs(candidate_lengths - target))]
xbar = xmin + 0.07 * width
ybar = ymin + 0.075 * (ymax - ymin)
ax.plot([xbar, xbar + bar_length], [ybar, ybar], color='black', linewidth=2.0, solid_capstyle='butt')
ax.text(xbar + bar_length / 2, ybar - 0.027 * (ymax - ymin), f'{bar_length:g} µm', ha='center', va='top', fontsize=8)
fig.savefig(OUT_PDF, bbox_inches='tight', pad_inches=0.02)
fig.savefig(OUT_PNG, dpi=600, bbox_inches='tight', pad_inches=0.02)
plt.close(fig)
print()
print('PANEL A COMPLETE')
print('PDF:', OUT_PDF)
print('PNG:', OUT_PNG)
