from __future__ import annotations

import argparse
import json
import os
from concurrent.futures import ProcessPoolExecutor,as_completed
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

from strata_hierarchy.v071.block_preflight import (
    read_10x_cells_by_genes,
    normalized_expression_dense,
)
from strata_hierarchy.v071.resource_intake import sha256_file
from strata_hierarchy.v074.directional_comm import (
    freeze_support_floor,
    directional_state,
)
from strata_hierarchy.v074.channel_direction import (
    ChannelAuditConfig,
    channel_resolved_edge_metrics,
    compare_scalar_and_channel,
    audit_summary,
    choose_directional_representation,
)

SAMPLES=("alzheimers","gbm_reference_addon","healthy_reference","nondiseased_kidney","prcc")


def require(p):
    p=Path(p)
    if not p.exists():
        raise FileNotFoundError(p)
    return p


def writepq(df,path):
    pq.write_table(
        pa.Table.from_pandas(df,preserve_index=False),
        path,
        compression="zstd",
    )


def locate_registry(project:Path,sample:str):
    # Prefer specimen-specific canonical registry generated by v0.7.1.
    p=project/"results"/"hierarchy_v071_active_blocks"/sample/"canonical_signaling_registry.parquet"
    if p.exists():
        return p
    # Fallback pinned resource snapshot if specimen copy is absent.
    p=project/"resources"/"strata_hierarchy_v0711"/"signaling"/"cellchat_typed_interactions.csv"
    if p.exists():
        return p
    raise FileNotFoundError("canonical CellChat signaling registry not found")


def read_registry(path:Path):
    if path.suffix.lower()==".parquet":
        return pd.read_parquet(path)
    return pd.read_csv(path,low_memory=False)


def one(project_s,sample,q):
    os.environ.update(
        OMP_NUM_THREADS="1",
        OPENBLAS_NUM_THREADS="1",
        VECLIB_MAXIMUM_THREADS="1",
        MKL_NUM_THREADS="1",
    )

    project=Path(project_s)
    l0=project/"results"/"hierarchy_level0_v070"/sample
    v72=project/"results"/"hierarchy_v072_short_pilot"/sample

    edge_rel=pd.read_parquet(
        require(v72/"level0_candidate_relations.parquet")
    )
    registry_path=locate_registry(project,sample)
    registry=read_registry(registry_path)

    manifest=json.loads(
        require(l0/"expression_manifest.json").read_text()
    )
    matrix=Path(manifest["source_matrix"])
    if sha256_file(matrix)!=manifest["source_matrix_sha256"]:
        raise RuntimeError(f"{sample}: expression source hash changed")

    X,barcodes,genes=read_10x_cells_by_genes(matrix)
    Y=normalized_expression_dense(X)

    if len(Y)<=max(
        int(edge_rel.cell_i_index.max()),
        int(edge_rel.cell_j_index.max())
    ):
        raise RuntimeError(f"{sample}: edge cell index exceeds expression matrix")

    cfg=ChannelAuditConfig()
    floor_meta=freeze_support_floor(edge_rel,q)
    floor=float(floor_meta["support_floor"])

    scalar=directional_state(
        edge_rel.comm_ij.to_numpy(np.float64),
        edge_rel.comm_ji.to_numpy(np.float64),
        floor,
        cfg.eps,
    )

    edge_metrics,channel_summary=channel_resolved_edge_metrics(
        Y,
        edge_rel,
        tuple(map(str,genes)),
        registry,
        cfg,
    )

    comparison=compare_scalar_and_channel(
        scalar.comm_directionality.to_numpy(np.float64),
        scalar.comm_supported.to_numpy(bool),
        edge_metrics,
        cfg,
    )

    # Preserve Level-0 interface identity/index columns for later spatial plots.
    id_cols=[
        c for c in [
            "cell_i_index","cell_j_index",
            "interface_id","cell_i","cell_j",
        ]
        if c in edge_rel.columns
    ]
    edge_out=pd.concat(
        [
            edge_rel[id_cols].reset_index(drop=True),
            scalar.reset_index(drop=True),
            edge_metrics.reset_index(drop=True),
            comparison[
                [
                    "scalar_signed_directionality",
                    "scalar_abs_directionality",
                    "hidden_directionality",
                    "cancellation_present",
                ]
            ].reset_index(drop=True),
        ],
        axis=1,
    )

    summary=audit_summary(comparison,edge_metrics,cfg)
    choice=choose_directional_representation(summary)

    out=project/"results"/"hierarchy_v0743_channel_direction_audit"/sample
    out.mkdir(parents=True,exist_ok=True)

    writepq(
        edge_out,
        out/"channel_resolved_edge_directionality.parquet"
    )
    writepq(
        channel_summary,
        out/"interaction_channel_statistics.parquet"
    )

    # Compact tables designed directly for later figures.
    fig_cols=[
        c for c in [
            *id_cols,
            "comm_support",
            "comm_supported",
            "scalar_signed_directionality",
            "scalar_abs_directionality",
            "channel_signed_net",
            "channel_net_asymmetry",
            "channel_directional_content",
            "channel_cancellation",
            "hidden_directionality",
            "contact_directional_content",
            "contact_cancellation",
            "diffusible_directional_content",
            "diffusible_cancellation",
        ]
        if c in edge_out.columns
    ]
    writepq(
        edge_out[fig_cols],
        out/"figure_ready_channel_directionality.parquet"
    )

    report={
        "sample":sample,
        "support_floor":floor_meta,
        "registry_path":str(registry_path),
        "registry_sha256":sha256_file(registry_path),
        "n_panel_supported_channels":int(
            channel_summary.shape[0]
        ),
        "channel_kinds":sorted(
            channel_summary.kind.astype(str).unique().tolist()
        ),
        "audit":summary,
        "representation_choice":choice,
        "hierarchy_rerun_performed":False,
        "level0_only":True,
    }
    report["status"]="PASS" if choice["status"]=="PASS" else "HOLD"

    (out/"channel_direction_audit.json").write_text(
        json.dumps(report,indent=2)+"\n"
    )
    return report


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--project-root",default=".")
    ap.add_argument("--workers",type=int,default=3)
    ap.add_argument("--comm-support-positive-quantile",type=float,default=0.10)
    a=ap.parse_args()

    project=Path(a.project_root).resolve()
    cert=require(
        project/"results"/"hierarchy_v0742_effective_flow"/
        "effective_flow_v0742_certificate.json"
    )
    d=json.loads(cert.read_text())
    if d.get("READY_FOR_DIRECTIONAL_LOCAL_METRIC") is not True:
        raise SystemExit("ERROR: v0.7.4.2 readiness gate is not PASS")

    print("STRATA 0.7.4.3 | Channel-resolved communication direction audit")
    print("No hierarchy rerun.")
    print("Auditing whether scalar communication hides opposing directional channels.")
    print("Panel-supported CellChat interactions are reconstructed individually.")
    print(f"Parallel specimens: {min(a.workers,len(SAMPLES))}\n")

    reports=[]
    with ProcessPoolExecutor(max_workers=min(a.workers,len(SAMPLES))) as ex:
        futs={
            ex.submit(
                one,str(project),s,
                a.comm_support_positive_quantile
            ):s
            for s in SAMPLES
        }
        for f in as_completed(futs):
            r=f.result()
            reports.append(r)
            au=r["audit"]
            print(
                f"[DONE] {r['sample']}: "
                f"channels={r['n_panel_supported_channels']} "
                f"hidden={100*au['hidden_directionality_fraction_supported']:.2f}% "
                f"cancel={100*au['cancellation_present_fraction_supported']:.2f}% "
                f"dir_q90={au['channel_directional_content_q90']:.3f} "
                f"{r['status']}",
                flush=True,
            )

    reports.sort(key=lambda x:SAMPLES.index(x["sample"]))
    gate=all(r["status"]=="PASS" for r in reports)

    out=project/"results"/"hierarchy_v0743_channel_direction_audit"
    out.mkdir(parents=True,exist_ok=True)

    cert_out={
        "strata_version":"0.7.4.3",
        "stage":"channel-resolved directed communication audit",
        "source_v0742_certificate_sha256":sha256_file(cert),
        "scientific_question":(
            "Does scalar communication aggregation erase directional ligand-receptor "
            "content through cancellation?"
        ),
        "definitions":{
            "net_asymmetry":"abs(sum(delta_r))/sum(weight_r)",
            "directional_content":"sum(abs(delta_r))/sum(weight_r)",
            "cancellation":"1-abs(sum(delta_r))/sum(abs(delta_r))",
            "delta_r":"forward_r-reverse_r",
            "weight_r":"forward_r+reverse_r",
        },
        "sample_reports":reports,
        "CHANNEL_DIRECTION_AUDIT_GATE":"PASS" if gate else "HOLD",
        "DIRECTIONAL_REPRESENTATION_READY":bool(gate),
        "recommended_next_representation":(
            "channel_resolved_signed_contributions" if gate else None
        ),
    }

    p=out/"channel_direction_audit_certificate.json"
    p.write_text(json.dumps(cert_out,indent=2)+"\n")

    print(f"\nCHANNEL DIRECTION AUDIT GATE: {cert_out['CHANNEL_DIRECTION_AUDIT_GATE']}")
    print(f"DIRECTIONAL REPRESENTATION READY: {cert_out['DIRECTIONAL_REPRESENTATION_READY']}")
    print(f"Recommended: {cert_out['recommended_next_representation']}")
    print(f"Certificate: {p}")


if __name__=="__main__":
    main()
