# PANEL-ONLY PRESENTATION COPY — generated by SUTRA_PANEL_ONLY_CANONICAL_V0_2
# Scientific calculations/data access are unchanged; only axes/figure titles and literal panel letters are suppressed.
from pathlib import Path
import argparse, json
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from matplotlib import gridspec
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
from matplotlib.colors import Normalize
import pyarrow.parquet as pq
CASES = ['epsilon_low', 'epsilon_ceiling', 'rescue_tighter', 'rescue_looser', 'soft_early', 'soft_late', 'frontier_low', 'frontier_high', 'eps_low_soft_late', 'eps_rescue_high_soft_early']
LABELS = {'epsilon_low': 'threshold ↓', 'epsilon_ceiling': 'threshold ceiling', 'rescue_tighter': 'rescue tighter', 'rescue_looser': 'rescue looser', 'soft_early': 'schedule early', 'soft_late': 'schedule late', 'frontier_low': 'frontier ↓', 'frontier_high': 'frontier ↑', 'eps_low_soft_late': 'joint: threshold + schedule', 'eps_rescue_high_soft_early': 'joint: rescue + schedule'}
FAMILY = {'epsilon_low': 'threshold', 'epsilon_ceiling': 'threshold', 'rescue_tighter': 'rescue', 'rescue_looser': 'rescue', 'soft_early': 'schedule', 'soft_late': 'schedule', 'frontier_low': 'frontier', 'frontier_high': 'frontier', 'eps_low_soft_late': 'joint', 'eps_rescue_high_soft_early': 'joint'}
FC = {'threshold': '#2878B5', 'rescue': '#3A923A', 'schedule': '#D88419', 'frontier': '#7953A6', 'joint': '#B0447A'}
METRICS = [('VI_bits_vs_ref', 'VI (bits)', 'Blues'), ('node_relerr_vs_ref', '|ΔN| / Nref', 'Greens'), ('top1_absdiff_vs_ref', '|Δ top-1% mass|', 'Oranges'), ('gini_absdiff_vs_ref', '|Δ Gini|', 'Reds')]

def rp(p, cols=None):
    return pq.ParquetFile(p).read(columns=cols, use_threads=False).to_pandas()

def canon(a):
    return np.unique(np.asarray(a), return_inverse=True)[1]

def xycols(df):
    lc = {c.lower(): c for c in df}
    for a, b in [('x_centroid', 'y_centroid'), ('centroid_x', 'centroid_y'), ('x', 'y'), ('x_location', 'y_location')]:
        if a in lc and b in lc:
            return (lc[a], lc[b])
    raise RuntimeError('No recognized x/y columns: ' + str(list(df.columns)))

def match(ref, pert):
    r = canon(ref)
    p = canon(pert)
    nr = int(r.max() + 1)
    u, c = np.unique(p.astype(np.int64) * nr + r, return_counts=True)
    best = {}
    for z, n in zip(u, c):
        pp = int(z // nr)
        rr = int(z % nr)
        if pp not in best or n > best[pp][0]:
            best[pp] = (int(n), rr)
    mp = {k: v[1] for k, v in best.items()}
    ch = np.array([mp.get(int(pp), -1) != int(rr) for pp, rr in zip(p, r)])
    return (r, p, mp, ch)

def crop(x, y, ch, bins=18, frac=0.3):
    xe = np.linspace(x.min(), x.max(), bins + 1)
    ye = np.linspace(y.min(), y.max(), bins + 1)
    H = np.zeros((bins, bins))
    C = np.zeros_like(H)
    ix = np.clip(np.digitize(x, xe) - 1, 0, bins - 1)
    iy = np.clip(np.digitize(y, ye) - 1, 0, bins - 1)
    for a, b, q in zip(ix, iy, ch):
        H[b, a] += 1
        C[b, a] += q
    S = C / np.maximum(H, 1)
    S[H < 15] = -1
    by, bx = np.unravel_index(np.argmax(S), S.shape)
    cx = (xe[bx] + xe[bx + 1]) / 2
    cy = (ye[by] + ye[by + 1]) / 2
    wx = (x.max() - x.min()) * frac
    wy = (y.max() - y.min()) * frac
    return (cx - wx / 2, cx + wx / 2, cy - wy / 2, cy + wy / 2)

def colors(ref, pert, mask):
    r, p, mp, ch = match(ref, pert)
    vals, cnt = np.unique(r[mask], return_counts=True)
    vals = vals[np.argsort(cnt)[::-1]][:14]
    cm = plt.get_cmap('tab20')
    rc = {int(v): cm(i % 20) for i, v in enumerate(vals)}
    neutral = (0.84, 0.84, 0.84, 1)
    a = np.array([rc.get(int(v), neutral) for v in r])
    b = np.array([rc.get(mp.get(int(v), -1), neutral) for v in p])
    return (a, b, ch)

def heat(ax, df, sample, title, norms):
    sub = df[(df.sample == sample) & df.case.isin(CASES)]
    ts = sorted(sub.target_removed_fraction.unique())
    W = len(ts)
    gap = 0.55
    for k, (m, lab, cmap) in enumerate(METRICS):
        z = np.full((10, W), np.nan)
        for i, c in enumerate(CASES):
            q = sub[sub.case == c].set_index('target_removed_fraction')
            for j, t in enumerate(ts):
                if t in q.index:
                    z[i, j] = q.loc[t, m]
        x0 = k * (W + gap)
        ax.imshow(z, origin='upper', aspect='auto', interpolation='none', extent=(x0 - 0.5, x0 + W - 0.5, 9.5, -0.5), cmap=cmap, norm=norms[m])
        ax.text(x0 + (W - 1) / 2, -1.25, lab, ha='center', va='bottom', fontsize=8.4, fontweight='bold')
        for j, t in enumerate(ts):
            ax.text(x0 + j, 10.05, f'{t:.2f}', rotation=45, ha='right', va='top', fontsize=6.4)
    ax.set_xlim(-0.5, 3 * (W + gap) + W - 0.5)
    ax.set_ylim(11.15, -1.85)
    ax.set_yticks(range(10))
    ax.set_yticklabels([LABELS[c] for c in CASES], fontsize=7.2)
    ax.set_xticks([])
    pass
    ax.text(np.mean(ax.get_xlim()), 11.0, 'matched removed fraction, u', ha='center', va='top', fontsize=7.3)
    ax.tick_params(length=0)
    for s in ax.spines.values():
        s.set_visible(False)

def panelA(fig, gs, root, part, meta):
    ax = fig.add_subplot(gs)
    ax.axis('off')
    pass
    ax.text(0.032, 1.018, 'Robustness mapping on the same measured tissue', fontsize=11.5, fontweight='bold', transform=ax.transAxes, va='top')
    candidates = [root / 'results/hierarchy_level0_v070/healthy_reference/cells.parquet', Path.home() / 'Desktop/SUTRA/results/hierarchy_level0_v070/healthy_reference/cells.parquet']
    cp = next((p for p in candidates if p.exists()), None)
    if cp is None:
        raise FileNotFoundError('Level-0 coordinate parquet not found at exact known paths')
    cells = rp(cp)
    xc, yc = xycols(cells)
    x = cells[xc].to_numpy(float)
    y = cells[yc].to_numpy(float)
    ref = part.reference_block.to_numpy()
    per = part.perturbed_block.to_numpy()
    if len(x) != len(ref):
        raise RuntimeError('coordinate/partition row mismatch')
    r, p, mp, ch = match(ref, per)
    box = crop(x, y, ch)
    m = (x >= box[0]) & (x <= box[1]) & (y >= box[2]) & (y <= box[3])
    cr, cpcol, ch = colors(ref, per, m)
    a0 = ax.inset_axes([0.035, 0.19, 0.18, 0.62])
    a0.scatter(x[m], y[m], s=4, c='.28', lw=0, rasterized=True)
    a0.axis('off')
    a0.set_aspect('equal')
    ax.text(0.125, 0.84, 'fixed Level-0 tissue', ha='center', fontsize=8.5, fontweight='bold', transform=ax.transAxes)
    ax.text(0.125, 0.13, 'same cells • same coordinates • same relational inputs', ha='center', fontsize=6.8, transform=ax.transAxes)
    ax.add_patch(FancyArrowPatch((0.22, 0.5), (0.275, 0.5), transform=ax.transAxes, arrowstyle='-|>', mutation_scale=11, lw=1, color='.3'))
    bx = 0.285
    ax.add_patch(FancyBboxPatch((bx, 0.25), 0.145, 0.5, transform=ax.transAxes, boxstyle='round,pad=.008,rounding_size=.01', fc='white', ec='.7', lw=0.8))
    ax.text(bx + 0.072, 0.68, 'controlled rule\nperturbation', ha='center', fontsize=8.1, fontweight='bold', transform=ax.transAxes)
    yy = 0.54
    for fam in ['threshold', 'rescue', 'schedule', 'frontier', 'joint']:
        ax.add_patch(Rectangle((bx + 0.025, yy - 0.012), 0.014, 0.014, transform=ax.transAxes, fc=FC[fam], ec='none'))
        ax.text(bx + 0.047, yy, fam, fontsize=6.9, va='center', transform=ax.transAxes)
        yy -= 0.055
    ax.text(bx + 0.072, 0.29, '$\\theta_{\\rm ref}\\rightarrow\\theta_p$', ha='center', fontsize=8.2, transform=ax.transAxes)
    ax.add_patch(FancyArrowPatch((0.44, 0.5), (0.485, 0.5), transform=ax.transAxes, arrowstyle='-|>', mutation_scale=11, lw=1, color='.3'))
    positions = [(0.49, 'reference', cr), (0.655, 'perturbed', cpcol)]
    for xx, ttl, cc in positions:
        aa = ax.inset_axes([xx, 0.23, 0.15, 0.56])
        aa.scatter(x[m], y[m], s=5, c=cc[m], lw=0, rasterized=True)
        aa.axis('off')
        aa.set_aspect('equal')
        ax.text(xx + 0.075, 0.82, ttl, ha='center', fontsize=8.2, fontweight='bold', transform=ax.transAxes)
    ad = ax.inset_axes([0.82, 0.23, 0.15, 0.56])
    ad.scatter(x[m], y[m], s=4, c='.88', lw=0, rasterized=True)
    ad.scatter(x[m & ch], y[m & ch], s=6, c='#222222', lw=0, rasterized=True)
    ad.axis('off')
    ad.set_aspect('equal')
    ax.text(0.895, 0.82, 'reassigned units', ha='center', fontsize=8.2, fontweight='bold', transform=ax.transAxes)
    ax.text(0.735, 0.12, f"matched u = {meta['target_removed_fraction']:.2f}     VI = {meta['VI_bits_recomputed']:.3f} bits", ha='center', fontsize=8.5, fontweight='bold', transform=ax.transAxes)
    ax.text(0.735, 0.075, 'block colors aligned by maximum membership overlap', ha='center', fontsize=6.7, color='.35', transform=ax.transAxes)

def bottomD(ax, brain, kidney):
    pass
    fams = ['threshold', 'rescue', 'schedule', 'frontier', 'joint']
    xs = np.arange(5)
    for org, df, samp, off, marker in [('brain', brain, 'healthy_reference', -0.1, 'o'), ('kidney', kidney, 'nondiseased_kidney', 0.1, 's')]:
        q = df[(df['sample'] == samp) & (df.case != 'reference')]
        g = q.groupby('case', as_index=False).max(numeric_only=True)
        for mi, (metric, lab, _) in enumerate([METRICS[0], METRICS[2], METRICS[3]]):
            pooled = np.nanmax(np.r_[brain.loc[brain.case != 'reference', metric], kidney.loc[kidney.case != 'reference', metric]])
            vals = []
            for fam in fams:
                cs = [c for c in CASES if FAMILY[c] == fam]
                z = g[g.case.isin(cs)][metric]
                vals.append(float(z.max()) / pooled if len(z) else np.nan)
            dx = (mi - 1) * 0.025
            for i, v in enumerate(vals):
                ax.scatter(i + off + dx, v, s=30, marker=marker, facecolors=FC[fams[i]] if mi == 0 else 'none', edgecolors=FC[fams[i]], linewidths=1)
    ax.set_xticks(xs, [f.replace('schedule', 'schedule') for f in fams], fontsize=7.5)
    ax.set_ylabel('response / pooled metric maximum', fontsize=8)
    ax.set_ylim(-0.04, 1.08)
    ax.tick_params(labelsize=7)
    ax.spines[['top', 'right']].set_visible(False)
    ax.text(0.98, 0.97, 'circle brain   square kidney\nfilled VI   open macro summaries', transform=ax.transAxes, ha='right', va='top', fontsize=6.8)

def bottomE(ax, bt, kt):
    pass
    data = []
    for yi, (org, tab, samp) in enumerate([('healthy brain', bt, 'healthy_reference'), ('nondiseased kidney', kt, 'nondiseased_kidney')]):
        q = tab[(tab['sample'] == samp) & (tab.case != 'reference')]
        for _, z in q.iterrows():
            data.append((yi, org, z.case, float(z.terminal_node_relerr_vs_ref), z.stop_reason))
    vmax = max((v for _, _, _, v, _ in data))
    for yi, org, c, v, stop in data:
        ax.scatter(v, yi + (CASES.index(c) - 4.5) * 0.018, s=28, c=FC[FAMILY[c]], edgecolors='white', linewidths=0.35)
    ax.set_yticks([0, 1], ['healthy brain', 'nondiseased kidney'], fontsize=7.8)
    ax.set_xlabel('terminal |ΔN| / Nref', fontsize=8)
    ax.set_xlim(-0.005, vmax * 1.08)
    ax.set_ylim(1.28, -0.28)
    ax.tick_params(labelsize=7)
    ax.spines[['top', 'right']].set_visible(False)
    ok = sum((s == 'no_contextually_admissible_boundaries' for *_, s in data))
    ax.text(0.98, 0.95, f'{ok}/{len(data)} retain endogenous exhaustion\n(no contextually admissible boundaries)', transform=ax.transAxes, ha='right', va='top', fontsize=7.6, fontweight='bold')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', type=Path, required=True)
    a = ap.parse_args()
    root = a.root.expanduser().resolve()
    out = root / 'results/Fig4_HRM'
    pdroot = out / 'v4_8_4_1_exact_partitions'
    meta = json.loads((pdroot / 'partition_materialization.json').read_text())
    part = rp(pdroot / f"healthy_reference_u0.55_{meta['case']}_partitions.parquet")
    brain = pd.read_csv(root / 'results/HRM_v0923/hrm_matched_trajectory.csv')
    kidney = pd.read_csv(root / 'results/HRM_v0923_kidney/hrm_matched_trajectory.csv')
    bt = pd.read_csv(root / 'results/HRM_v0923/hrm_terminal_summary.csv')
    kt = pd.read_csv(root / 'results/HRM_v0923_kidney/hrm_terminal_summary.csv')
    norms = {}
    for m, _, _ in METRICS:
        vals = np.r_[brain.loc[brain.case != 'reference', m].to_numpy(float), kidney.loc[kidney.case != 'reference', m].to_numpy(float)]
        norms[m] = Normalize(0, np.nanmax(vals))
    fig = plt.figure(figsize=(13, 11.0))
    G = gridspec.GridSpec(4, 2, figure=fig, height_ratios=[2.45, 2.45, 2.45, 1.72], hspace=0.27, wspace=0.22)
    panelA(fig, G[0, :], root, part, meta)
    heat(fig.add_subplot(G[1, :]), brain, 'healthy_reference', 'B   Healthy brain', norms)
    heat(fig.add_subplot(G[2, :]), kidney, 'nondiseased_kidney', 'C   Nondiseased kidney', norms)
    bottomD(fig.add_subplot(G[3, 0]), brain, kidney)
    bottomE(fig.add_subplot(G[3, 1]), bt, kt)
    fig.text(0.5, 0.008, "Continuous HRM deviations are relative to each organ's within-HRM reference; engineering certification is not treated as a biological failure label.", ha='center', fontsize=7)
    fig.savefig(out / 'SUTRA_Fig4_HRM_v4_10.png', dpi=400, bbox_inches='tight')
    fig.savefig(out / 'SUTRA_Fig4_HRM_v4_10.pdf', bbox_inches='tight')
    print('WROTE', out / 'SUTRA_Fig4_HRM_v4_10.png')
    print('WROTE', out / 'SUTRA_Fig4_HRM_v4_10.pdf')
if __name__ == '__main__':
    main()
