# PANEL-ONLY PRESENTATION COPY — generated by SUTRA_PANEL_ONLY_CANONICAL_V0_2
# Scientific calculations/data access are unchanged; only axes/figure titles and literal panel letters are suppressed.
from pathlib import Path
import json
import re
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.gridspec import GridSpec, GridSpecFromSubplotSpec
from matplotlib.colors import Normalize, TwoSlopeNorm
from matplotlib.collections import LineCollection
warnings.filterwarnings('ignore')
ROOT = Path.home() / 'Desktop' / 'SUTRA'
RES = ROOT / 'results'
GW3 = RES / 'Fig5_Disease_Trajectories' / 'gw_multistart_dense_v5'
BIO4 = RES / 'Fig5_Disease_Trajectories' / 'gw_biology_dense_v5'
CF13 = RES / 'Fig5_Disease_Trajectories' / 'consolidation_field_v13'
EX12 = RES / 'Exact_Consolidation_v12' / 'prcc'
OUT = RES / 'Main_Fig5_FINE'
OUT.mkdir(parents=True, exist_ok=True)
gw_summary = pd.read_csv(GW3 / 'multistart_scale_summary.csv').sort_values('u_target')
GW_U = gw_summary['u_target'].to_numpy(float)
GW_D = gw_summary['best_gw_distance'].to_numpy(float)
if len(GW_U) != 25:
    raise RuntimeError(f'Expected 25 dense GW states, found {len(GW_U)}')
mpl.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 8.5, 'axes.titlesize': 9.5, 'axes.labelsize': 8.5, 'xtick.labelsize': 7.5, 'ytick.labelsize': 7.5, 'legend.fontsize': 7, 'axes.linewidth': 0.8, 'pdf.fonttype': 42, 'ps.fonttype': 42})

def clean(ax):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

def square_domain(ax, X, Y, pad=0.035):
    x = np.asarray(X, float)
    y = np.asarray(Y, float)
    xmin, xmax = (np.nanmin(x), np.nanmax(x))
    ymin, ymax = (np.nanmin(y), np.nanmax(y))
    cx, cy = ((xmin + xmax) / 2, (ymin + ymax) / 2)
    side = max(xmax - xmin, ymax - ymin) * (1 + 2 * pad)
    ax.set_xlim(cx - side / 2, cx + side / 2)
    ax.set_ylim(cy - side / 2, cy + side / 2)
    ax.set_aspect('equal', adjustable='box')

def letter(ax, s):
    ax.text(-0.12, 1.08, s, transform=ax.transAxes, fontsize=18, fontweight='bold', va='top', ha='left', clip_on=False)

def save_single(fig, name):
    fig.savefig(OUT / f'{name}.pdf', bbox_inches='tight', facecolor='white')
    fig.savefig(OUT / f'{name}.png', dpi=450, bbox_inches='tight', facecolor='white')
    plt.close(fig)
field_file = CF13 / 'prcc_consolidation_field.npz'
if not field_file.exists():
    raise FileNotFoundError(field_file)
Z = np.load(field_file, allow_pickle=True)
print('FIELD NPZ KEYS')
print(Z.files)

def get_first(keys, required=True):
    for k in keys:
        if k in Z.files:
            return np.asarray(Z[k])
    if required:
        raise KeyError(f'Could not find any of {keys}')
    return None
C = get_first(['consolidation_median', 'consolidation_field', 'resolved_field', 'median_consolidation', 'field'])
P = get_first(['persistent_fraction', 'persistence_field', 'persistence'])
X = get_first(['x_centers', 'x_grid', 'grid_x', 'X'], required=False)
Y = get_first(['y_centers', 'y_grid', 'grid_y', 'Y'], required=False)
if X is None or Y is None:
    ny, nx = C.shape
    X = np.arange(nx)
    Y = np.arange(ny)
if X.ndim == 1 and Y.ndim == 1:
    XX, YY = np.meshgrid(X, Y)
else:
    XX, YY = (X, Y)
if C.shape != P.shape:
    raise RuntimeError(f'Consolidation and persistence field shapes differ: {C.shape} vs {P.shape}')
if 'support' in Z.files:
    support = np.asarray(Z['support']).astype(bool)
else:
    support = np.isfinite(C) | np.isfinite(P)
if support.shape != C.shape:
    raise RuntimeError(f'V13 support shape {support.shape} != field shape {C.shape}')
C = np.where(support, C, np.nan)
P = np.where(support, P, np.nan)

def nan_smooth(a, passes=2):
    a = np.asarray(a, float).copy()
    original_support = np.isfinite(a)
    for _ in range(passes):
        pad = np.pad(a, 1, constant_values=np.nan)
        stacks = []
        for di in range(3):
            for dj in range(3):
                stacks.append(pad[di:di + a.shape[0], dj:dj + a.shape[1]])
        with np.errstate(invalid='ignore'):
            b = np.nanmean(np.stack(stacks), axis=0)
        b[~original_support] = np.nan
        a = b
    return a
Cs = nan_smooth(C, passes=2)
Ps = nan_smooth(P, passes=2)
finite_c = C[np.isfinite(C)]
if finite_c.size == 0:
    raise RuntimeError('No finite consolidation-field values.')
levels = np.quantile(finite_c, [0.1, 0.3, 0.5, 0.7, 0.9])
bio_file = BIO4 / 'molecular' / 'gene_continuous_association_all_scales.csv'
B = pd.read_csv(bio_file)
needed = {'u', 'gene', 'object_spearman_sqrt_mass'}
missing = needed - set(B.columns)
if missing:
    raise RuntimeError(f'Missing required V4 biology columns: {sorted(missing)}')
target_scales = [round(float(x), 2) for x in np.arange(0.08, 0.560001, 0.02)]
B = B.copy()
B['scale_match'] = B['u'].astype(float).round(2)
PIV = B[B['scale_match'].isin(target_scales)].pivot_table(index='gene', columns='scale_match', values='object_spearman_sqrt_mass', aggfunc='mean')
PIV = PIV.dropna(subset=target_scales)
dynamic = PIV[target_scales].max(axis=1) - PIV[target_scales].min(axis=1)
strength = PIV[target_scales].abs().max(axis=1)
selection_score = dynamic + 0.35 * strength
genes = selection_score.sort_values(ascending=False).head(12).index.tolist()
H = PIV.loc[genes, target_scales]
print('\nALGORITHMICALLY SELECTED GENES')
for g in genes:
    print(f'{g:12s} score={selection_score[g]:.4f} range={dynamic[g]:.4f} maxabs={strength[g]:.4f}')
fig, ax = plt.subplots(figsize=(5.0, 3.6))
uf = np.linspace(GW_U.min(), GW_U.max(), 500)
df = np.interp(uf, GW_U, GW_D)
ax.plot(uf, df, lw=1.3, alpha=0.55, label='guide between evaluated states')
ax.scatter(GW_U, GW_D, s=40, zorder=4, edgecolor='black', linewidth=0.55, label='evaluated GW states')
ax.set_xlabel('Hierarchy progression, $u$')
ax.set_ylabel('GW relational displacement')
ax.set_xlim(0.06, 0.58)
ax.set_xticks(np.arange(0.08, 0.57, 0.08))
clean(ax)
letter(ax, 'A')
ax.legend(frameon=False, loc='upper left')
save_single(fig, 'Fig5A_GW')
fig, ax = plt.subplots(figsize=(5.5, 4.5))
m = ax.pcolormesh(XX, YY, Cs, shading='auto', cmap='viridis', rasterized=True)
ax.set_aspect('equal')
ax.axis('off')
letter(ax, 'B')
cb = fig.colorbar(m, ax=ax, fraction=0.035, pad=0.02)
cb.set_label('Exact consolidation coordinate, $u_c$')
save_single(fig, 'Fig5B_consolidation_field')
iso_levels = [levels[0], levels[2], levels[4]]
fig = plt.figure(figsize=(12.2, 4.0))
gs = GridSpec(1, 3, figure=fig, left=0.035, right=0.985, bottom=0.08, top=0.88, wspace=0.13)
for j, lev in enumerate(iso_levels):
    ax = fig.add_subplot(gs[0, j])
    bg = np.where(np.isfinite(Cs), Cs, np.nan)
    ax.pcolormesh(XX, YY, bg, shading='auto', cmap='Greys', vmin=np.nanmin(Cs), vmax=np.nanmax(Cs), alpha=0.12, rasterized=True)
    try:
        ax.contour(XX, YY, Cs, levels=[lev], colors='black', linewidths=1.35)
    except Exception as e:
        print('Contour warning:', e)
    pass
    ax.set_aspect('equal')
    ax.axis('off')
    if j == 0:
        letter(ax, 'C')
fig.text(0.5, 0.96, 'Iso-consolidation contours', ha='center', va='top', fontsize=11, fontweight='bold')
save_single(fig, 'Fig5C_iso_consolidation')
fig, ax = plt.subplots(figsize=(5.5, 4.5))
m = ax.pcolormesh(XX, YY, Ps, shading='auto', cmap='magma', vmin=0, vmax=1, rasterized=True)
ax.set_aspect('equal')
ax.axis('off')
letter(ax, 'D')
cb = fig.colorbar(m, ax=ax, fraction=0.035, pad=0.02)
cb.set_label('Persistent-interface fraction')
save_single(fig, 'Fig5D_persistence')
fig, ax = plt.subplots(figsize=(5.5, 5.2))
lim = float(np.nanmax(np.abs(H.values)))
norm = TwoSlopeNorm(vmin=-lim, vcenter=0, vmax=lim)
im = ax.imshow(H.values, aspect='auto', cmap='coolwarm', norm=norm, interpolation='nearest')
ax.set_xticks(np.arange(len(target_scales)))
ax.set_xticklabels([f'{x:.2f}' for x in target_scales])
ax.set_yticks(np.arange(len(genes)))
ax.set_yticklabels(genes)
ax.set_xlabel('Hierarchy progression, $u$')
ax.set_ylabel('Gene')
cb = fig.colorbar(im, ax=ax, fraction=0.045, pad=0.03)
cb.set_label('Object-level gene–GW association\n(mass-weighted Spearman)')
for i, g in enumerate(genes):
    vals = H.loc[g].values
    signs = np.sign(vals)
    reversal = np.any(signs[:-1] * signs[1:] < 0)
    if reversal:
        ax.text(len(target_scales) - 0.06, i, '•', ha='left', va='center', fontsize=11, clip_on=False)
letter(ax, 'E')
save_single(fig, 'Fig5E_molecular_scale')
fig = plt.figure(figsize=(14.2, 10.4))
outer = GridSpec(3, 1, figure=fig, height_ratios=[0.92, 1.18, 1.02], left=0.05, right=0.97, bottom=0.06, top=0.97, hspace=0.22)
r0 = GridSpecFromSubplotSpec(1, 2, subplot_spec=outer[0], width_ratios=[0.82, 1.18], wspace=0.2)
axA = fig.add_subplot(r0[0, 0])
axA.plot(GW_U, GW_D, lw=1.15, alpha=0.7, zorder=2)
axA.scatter(GW_U, GW_D, s=24, edgecolor='black', linewidth=0.4, zorder=4)
axA.set_xlabel('Hierarchy progression, $u$')
axA.set_ylabel('GW relational displacement')
axA.set_xlim(0.06, 0.58)
axA.set_xticks(np.arange(0.08, 0.57, 0.08))
clean(axA)
letter(axA, 'A')
axB = fig.add_subplot(r0[0, 1])
mB = axB.pcolormesh(XX, YY, Cs, shading='auto', cmap='viridis', rasterized=True)
square_domain(axB, XX, YY)
axB.axis('off')
letter(axB, 'B')
axB.text(0.02, 0.02, 'local consolidation scale', transform=axB.transAxes, fontsize=7.5, ha='left', va='bottom', bbox=dict(facecolor='white', edgecolor='none', alpha=0.78, pad=2))
cb = fig.colorbar(mB, ax=axB, fraction=0.026, pad=0.012)
cb.set_label('earlier  ←  consolidation coordinate $u_c$  →  later')
r1 = GridSpecFromSubplotSpec(1, 2, subplot_spec=outer[1], width_ratios=[1.55, 0.9], wspace=0.16)
axC = fig.add_subplot(r1[0, 0])
axC.pcolormesh(XX, YY, np.where(support, 1.0, np.nan), shading='auto', cmap='Greys', vmin=0, vmax=1, alpha=0.07, rasterized=True)
contour_levels = np.unique(np.asarray(levels, float))
line_widths = np.linspace(0.75, 1.75, len(contour_levels))
cs = axC.contour(XX, YY, Cs, levels=contour_levels, cmap='viridis', linewidths=line_widths)
pass
square_domain(axC, XX, YY)
axC.axis('off')
letter(axC, 'C')
keytxt = '  '.join([f'{v:.2f}' for v in contour_levels])
axC.text(0.5, 0.985, '$u_c$: ' + keytxt, transform=axC.transAxes, ha='center', va='top', fontsize=7.3, bbox=dict(facecolor='white', edgecolor='none', alpha=0.86, pad=2))
axD = fig.add_subplot(r1[0, 1])
mD = axD.pcolormesh(XX, YY, Ps, shading='auto', cmap='magma', vmin=0, vmax=1, rasterized=True)
pass
square_domain(axD, XX, YY)
axD.axis('off')
letter(axD, 'D')
axD.text(0.02, 0.02, 'persistent to natural exhaustion', transform=axD.transAxes, fontsize=7.3, ha='left', va='bottom', bbox=dict(facecolor='white', edgecolor='none', alpha=0.78, pad=2))
cb = fig.colorbar(mD, ax=axD, fraction=0.035, pad=0.014)
cb.set_label('local persistent-interface fraction')
axE = fig.add_subplot(outer[2])
lim = float(np.nanmax(np.abs(H.values)))
im = axE.imshow(H.values, aspect='auto', cmap='coolwarm', norm=TwoSlopeNorm(vmin=-lim, vcenter=0, vmax=lim), interpolation='nearest')
tick_idx = np.arange(0, len(target_scales), 2)
axE.set_xticks(tick_idx)
axE.set_xticklabels([f'{target_scales[i]:.2f}' for i in tick_idx])
axE.set_yticks(np.arange(len(genes)))
axE.set_yticklabels(genes)
axE.set_xlabel('Hierarchy progression, $u$')
axE.set_ylabel('Gene')
letter(axE, 'E')
cb = fig.colorbar(im, ax=axE, fraction=0.018, pad=0.016)
cb.set_label('Object-level gene–GW association (mass-weighted Spearman)')
fig.savefig(OUT / 'Main_Fig5_FINE.pdf', bbox_inches='tight', facecolor='white')
fig.savefig(OUT / 'Main_Fig5_FINE.png', dpi=450, bbox_inches='tight', facecolor='white')
plt.close(fig)
prov = {'version': 'Main_Fig5_FINE', 'gw_source': str(GW3), 'gw_actual_evaluated_states': GW_U.tolist(), 'gw_intermediate_values_computed': True, 'gw_connecting_curve': 'line connects 25 genuinely evaluated hierarchy states', 'consolidation_source': str(CF13), 'exact_edge_source': str(EX12), 'iso_name': 'iso-consolidation contours', 'iso_levels': [float(x) for x in contour_levels], 'iso_contours_displayed_together': True, 'field_display_smoothing': 'two local nan-mean passes restricted to authoritative V13 support', 'spatial_extrapolation': False, 'molecular_source': str(bio_file), 'molecular_metric': 'object_spearman_sqrt_mass', 'gene_selection': 'top 12 by dynamic range + 0.35*maximum absolute object-level association among genes observed at all four scales', 'gene_selection_not_handpicked': True, 'claim': 'PRCC relational displacement is spatially organized and its molecular associations reorganize with organizational scale.'}
(OUT / 'provenance.json').write_text(json.dumps(prov, indent=2))
print('\nWROTE:', OUT)
for p in sorted(OUT.iterdir()):
    print(' ', p.name)
