# PANEL-ONLY PRESENTATION COPY — generated by SUTRA_PANEL_ONLY_CANONICAL_V0_2
# Scientific calculations/data access are unchanged; only axes/figure titles and literal panel letters are suppressed.
from pathlib import Path
import json
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.gridspec import GridSpec, GridSpecFromSubplotSpec
from matplotlib.colors import Normalize
warnings.filterwarnings('ignore')
ROOT = Path.home() / 'Desktop' / 'SUTRA'
RES = ROOT / 'results'
SRC = RES / 'Fig6_Consolidation_Prediction' / 'restricted_dense_v4'
OUT = RES / 'Main_Fig6_FINE'
OUT.mkdir(parents=True, exist_ok=True)
SAMPLES = [('healthy_reference', 'Healthy brain'), ('nondiseased_kidney', 'Nondiseased kidney')]
mpl.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 8.5, 'axes.titlesize': 9.5, 'axes.labelsize': 8.5, 'xtick.labelsize': 7.5, 'ytick.labelsize': 7.5, 'legend.fontsize': 7, 'axes.linewidth': 0.8, 'pdf.fonttype': 42, 'ps.fonttype': 42})

def clean(ax):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

def letter(ax, s):
    ax.text(-0.13, 1.1, s, transform=ax.transAxes, fontsize=18, fontweight='bold', ha='left', va='top', clip_on=False)
PERF = pd.read_csv(SRC / 'performance_all.csv')
MEAN = pd.read_csv(SRC / 'performance_means.csv')
IMP = pd.read_csv(SRC / 'permutation_importance.csv')
MAP = {}
for s, _ in SAMPLES:
    MAP[s] = pd.read_parquet(SRC / f'{s}_oof_predictions.parquet')

def spatial_scatter(ax, df, value, title, cmap, vmin=None, vmax=None):
    x = df['x_plot'].values
    y = df['y_plot'].values
    z = df[value].values
    ok = np.isfinite(x) & np.isfinite(y) & np.isfinite(z)
    sc = ax.scatter(x[ok], y[ok], c=z[ok], s=1.05, cmap=cmap, vmin=vmin, vmax=vmax, linewidths=0, rasterized=True)
    pass
    xmin, xmax = (np.nanmin(x[ok]), np.nanmax(x[ok]))
    ymin, ymax = (np.nanmin(y[ok]), np.nanmax(y[ok]))
    cx, cy = ((xmin + xmax) / 2, (ymin + ymax) / 2)
    side = max(xmax - xmin, ymax - ymin) * 1.06
    ax.set_xlim(cx - side / 2, cx + side / 2)
    ax.set_ylim(cy - side / 2, cy + side / 2)
    ax.set_aspect('equal', adjustable='box')
    ax.axis('off')
    return sc
fig = plt.figure(figsize=(15.5, 12.8))
outer = GridSpec(4, 1, figure=fig, height_ratios=[1.08, 1.08, 1.03, 1.08], left=0.045, right=0.975, bottom=0.05, top=0.97, hspace=0.27)
for row, (sample, label) in enumerate(SAMPLES):
    df = MAP[sample]
    gs = GridSpecFromSubplotSpec(1, 4, subplot_spec=outer[row], wspace=0.13)
    axes = [fig.add_subplot(gs[0, j]) for j in range(4)]
    spatial_scatter(axes[0], df, 'observed_persistent', 'Observed interface fate', 'coolwarm', vmin=0, vmax=1)
    spatial_scatter(axes[1], df, 'predicted_persistent_probability', 'Held-out persistence probability', 'coolwarm', vmin=0, vmax=1)
    uobs = df['observed_consolidation_u'].values
    finite = np.isfinite(uobs)
    if finite.any():
        umin = float(np.nanquantile(uobs[finite], 0.01))
        umax = float(np.nanquantile(uobs[finite], 0.99))
    else:
        umin, umax = (0, 1)
    spatial_scatter(axes[2], df, 'observed_consolidation_u', 'Observed exact consolidation scale', 'viridis', vmin=umin, vmax=umax)
    spatial_scatter(axes[3], df, 'predicted_consolidation_u', 'Held-out predicted scale', 'viridis', vmin=umin, vmax=umax)
    letter(axes[0], 'A' if row == 0 else 'B')
    bbox = axes[1].get_position()
    bbox2 = axes[2].get_position()
    center = (bbox.x0 + bbox2.x1) / 2
    fig.text(center, max((a.get_position().y1 for a in axes)) + 0.025, label, ha='center', va='bottom', fontsize=12, fontweight='bold')
row2 = GridSpecFromSubplotSpec(1, 2, subplot_spec=outer[2], width_ratios=[1.0, 1.05], wspace=0.27)
cgs = GridSpecFromSubplotSpec(1, 2, subplot_spec=row2[0], wspace=0.27)
axC1 = fig.add_subplot(cgs[0, 0])
axC2 = fig.add_subplot(cgs[0, 1])
classes = ['geometry', 'geometry_topology', 'geometry_topology_mechanics']
class_labels = ['Geometry', '+ topology', '+ mechanics']
for sample, label in SAMPLES:
    sub = PERF[(PERF['sample'] == sample) & (PERF['analysis'] == 'information_class') & (PERF['task'] == 'persistence')]
    xs = []
    ys = []
    for i, c in enumerate(classes):
        q = sub[sub['information_class'] == c]
        xs.extend(np.full(len(q), i, dtype=float))
        ys.extend(q['auc'].values)
    axC1.scatter(xs, ys, s=20, alpha=0.7, label=label)
    means = [sub[sub['information_class'] == c]['auc'].mean() for c in classes]
    axC1.scatter(range(3), means, s=62, marker='_', linewidths=2.4, zorder=5)
    sub = PERF[(PERF['sample'] == sample) & (PERF['analysis'] == 'information_class') & (PERF['task'] == 'consolidation_scale')]
    xs = []
    ys = []
    for i, c in enumerate(classes):
        q = sub[sub['information_class'] == c]
        xs.extend(np.full(len(q), i, dtype=float))
        ys.extend(100 * q['mae_improvement'].values)
    axC2.scatter(xs, ys, s=20, alpha=0.7)
    means = [100 * sub[sub['information_class'] == c]['mae_improvement'].mean() for c in classes]
    axC2.scatter(range(3), means, s=62, marker='_', linewidths=2.4, zorder=5)
axC1.axhline(0.5, ls='--', lw=0.8, alpha=0.5)
axC1.set_ylabel('Held-out persistence ROC AUC')
axC1.set_xticks(range(3))
axC1.set_xticklabels(class_labels, rotation=0, ha='center')
clean(axC1)
letter(axC1, 'C')
axC1.legend(frameon=False, loc='lower right')
axC2.axhline(0, ls='--', lw=0.8, alpha=0.5)
axC2.set_ylabel('Consolidation-scale\nMAE improvement (%)')
axC2.set_xticks(range(3))
axC2.set_xticklabels(class_labels, rotation=0, ha='center')
clean(axC2)
dgs = GridSpecFromSubplotSpec(1, 2, subplot_spec=row2[1], wspace=0.32)
axD1 = fig.add_subplot(dgs[0, 0])
axD2 = fig.add_subplot(dgs[0, 1])
for sample, label in SAMPLES:
    q = MEAN[(MEAN['sample'] == sample) & (MEAN['analysis'] == 'horizon') & (MEAN['task'] == 'persistence')].sort_values('horizon')
    axD1.plot(q['horizon'], q['auc'], marker='o', lw=1.7, label=label)
    q = MEAN[(MEAN['sample'] == sample) & (MEAN['analysis'] == 'horizon') & (MEAN['task'] == 'consolidation_scale')].sort_values('horizon')
    axD2.plot(q['horizon'], 100 * q['mae_improvement'], marker='o', lw=1.7, label=label)
axD1.axhline(0.5, ls='--', lw=0.8, alpha=0.5)
axD1.set_xlabel('Hierarchy horizon, $h$')
axD1.set_ylabel('Persistence ROC AUC')
axD1.set_xticks([0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3])
clean(axD1)
letter(axD1, 'D')
axD2.axhline(0, ls='--', lw=0.8, alpha=0.5)
axD2.set_xlabel('Hierarchy horizon, $h$')
axD2.set_ylabel('MAE improvement (%)')
axD2.set_xticks([0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3])
clean(axD2)
axD2.legend(frameon=False, loc='best')
row3 = GridSpecFromSubplotSpec(1, 2, subplot_spec=outer[3], width_ratios=[0.9, 1.1], wspace=0.27)
egs = GridSpecFromSubplotSpec(1, 2, subplot_spec=row3[0], wspace=0.34)
axE1 = fig.add_subplot(egs[0, 0])
axE2 = fig.add_subplot(egs[0, 1])
for sample, label in SAMPLES:
    df = MAP[sample]
    p = df['predicted_persistent_probability'].values
    y = df['observed_persistent'].values
    ok = np.isfinite(p) & np.isfinite(y)
    p = p[ok]
    y = y[ok]
    bins = np.quantile(p, np.linspace(0, 1, 11))
    bins = np.unique(bins)
    bx = []
    by = []
    for lo, hi in zip(bins[:-1], bins[1:]):
        m = (p >= lo) & (p < hi if hi < bins[-1] else p <= hi)
        if m.sum() < 20:
            continue
        bx.append(np.mean(p[m]))
        by.append(np.mean(y[m]))
    axE1.plot(bx, by, marker='o', lw=1.5, label=label)
    p = df['predicted_consolidation_u'].values
    y = df['observed_consolidation_u'].values
    ok = np.isfinite(p) & np.isfinite(y)
    p = p[ok]
    y = y[ok]
    bins = np.quantile(p, np.linspace(0, 1, 11))
    bins = np.unique(bins)
    bx = []
    by = []
    for lo, hi in zip(bins[:-1], bins[1:]):
        m = (p >= lo) & (p < hi if hi < bins[-1] else p <= hi)
        if m.sum() < 20:
            continue
        bx.append(np.mean(p[m]))
        by.append(np.mean(y[m]))
    axE2.plot(bx, by, marker='o', lw=1.5)
axE1.plot([0, 1], [0, 1], ls='--', lw=0.8, alpha=0.5)
axE1.set_xlabel('Predicted persistence probability')
axE1.set_ylabel('Observed persistent fraction')
axE1.set_xlim(0, 1)
axE1.set_ylim(0, 1)
clean(axE1)
letter(axE1, 'E')
axE1.legend(frameon=False, loc='best')
all_u = np.concatenate([MAP[s]['observed_consolidation_u'].values for s, _ in SAMPLES])
all_u = all_u[np.isfinite(all_u)]
lo = float(np.nanmin(all_u))
hi = float(np.nanmax(all_u))
axE2.plot([lo, hi], [lo, hi], ls='--', lw=0.8, alpha=0.5)
axE2.set_xlabel('Predicted consolidation scale')
axE2.set_ylabel('Observed consolidation scale')
clean(axE2)
F = IMP.groupby(['sample', 'task', 'feature'], as_index=False)['importance'].mean()
tmp = []
for (s, t), q in F.groupby(['sample', 'task']):
    z = q.copy()
    denom = max(float(z['importance'].abs().max()), 1e-12)
    z['_norm'] = z['importance'].abs() / denom
    tmp.append(z)
T = pd.concat(tmp, ignore_index=True)
rank = T.groupby('feature')['_norm'].max().sort_values(ascending=False)
features = rank.head(9).index.tolist()
fgs = GridSpecFromSubplotSpec(1, 2, subplot_spec=row3[1], wspace=0.28)
axF1 = fig.add_subplot(fgs[0, 0])
axF2 = fig.add_subplot(fgs[0, 1])

def importance_panel(ax, task, xlabel, show_ylabels=True):
    y = np.arange(len(features))
    offsets = {'healthy_reference': -0.11, 'nondiseased_kidney': 0.11}
    for sample, label in SAMPLES:
        q = F[(F['sample'] == sample) & (F['task'] == task)].set_index('feature')
        vals = np.array([q.loc[f, 'importance'] if f in q.index else 0.0 for f in features])
        ax.scatter(vals, y + offsets[sample], s=28, label=label)
    ax.axvline(0, ls='--', lw=0.7, alpha=0.5)
    ax.set_yticks(y)
    if show_ylabels:
        ax.set_yticklabels(features)
    else:
        ax.set_yticklabels([])
        ax.tick_params(axis='y', length=0)
    ax.invert_yaxis()
    ax.set_xlabel(xlabel)
    clean(ax)
importance_panel(axF1, 'persistence', 'Held-out AUC loss\nafter permutation', show_ylabels=True)
letter(axF1, 'F')
importance_panel(axF2, 'consolidation_scale', 'Held-out MAE increase\nafter permutation', show_ylabels=False)
axF2.legend(frameon=False, loc='lower right')
fig.savefig(OUT / 'Main_Fig6_FINE.pdf', bbox_inches='tight', facecolor='white')
fig.savefig(OUT / 'Main_Fig6_FINE.png', dpi=450, bbox_inches='tight', facecolor='white')
plt.close(fig)
prov = {'version': 'Main_Fig6_FINE', 'source': str(SRC), 'main_claim': 'Fine-scale Level-0 geometry, topology and mechanics contain held-out information about subsequent organizational outcomes along the SUTRA hierarchy.', 'spatial_maps': 'out-of-fold predictions only', 'coordinate_predictors_used': False, 'spatial_block_predictors_used': False, 'fold_predictors_used': False, 'hierarchy_updated_predictors_used': False, 'hierarchy_merge_cost_variables_used': False, 'cross_tissue_transfer_in_main_figure': False, 'cross_tissue_transfer_destination': 'supplementary validation', 'fold_points': 'spatial validation partitions, not biological replicates', 'error_bars_interpreted_as_biological_replicates': False, 'layout': 'four compact explicit non-overlapping rows; no tight_layout'}
(OUT / 'provenance.json').write_text(json.dumps(prov, indent=2))
print('WROTE:', OUT)
for p in sorted(OUT.iterdir()):
    print(' ', p.name)
