# PANEL-ONLY PRESENTATION COPY — generated by SUTRA_PANEL_ONLY_CANONICAL_V0_2
# Scientific calculations/data access are unchanged; only axes/figure titles and literal panel letters are suppressed.
import argparse, json
from pathlib import Path
import numpy as np, pandas as pd, matplotlib.pyplot as plt
ap = argparse.ArgumentParser()
ap.add_argument('--main-results', required=True)
ap.add_argument('--output-root', required=True)
a = ap.parse_args()
base = Path(__file__).resolve().parents[1] / 'frozen_source/fig3'
out = Path(a.output_root) / 'main/Fig03'
out.mkdir(parents=True, exist_ok=True)

def save(fig, stem):
    fig.tight_layout()
    fig.savefig(out / f'{stem}.pdf', bbox_inches='tight')
    fig.savefig(out / f'{stem}.png', dpi=300, bbox_inches='tight')
    plt.close(fig)
for sample, letter, label in [('healthy_reference', 'A', 'Healthy brain'), ('nondiseased_kidney', 'B', 'Nondiseased kidney')]:
    d = pd.read_csv(base / f'{sample}_collective_pmf_event_states.csv')
    print(sample, d.columns.tolist())
    num = [c for c in d.columns if pd.api.types.is_numeric_dtype(d[c])]
    m = next((c for c in d.columns if c.lower() in ['m', 'mass', 'object_mass']), num[0])
    prob = next((c for c in d.columns if 'prob' in c.lower() or 'pmf' in c.lower()), num[-1])
    state = next((c for c in d.columns if 'state' in c.lower() or c.lower() in ['u', 'stage']), None)
    fig, ax = plt.subplots(figsize=(4.2, 3.4))
    groups = d.groupby(state) if state else [('observed', d)]
    for k, g in groups:
        ax.scatter(g[m], g[prob], s=8, alpha=0.65, label=str(k))
    ax.set_xscale('log')
    ax.set_yscale('log')
    ax.set_xlabel('Collective-object mass, m')
    ax.set_ylabel('P(m | m ≥ 2)')
    pass
    if state and d[state].nunique() <= 6:
        ax.legend(frameon=False, fontsize=7)
    save(fig, f'Fig3{letter}_collective_PMF')
for sample, letter, label in [('healthy_reference', 'C', 'Healthy brain'), ('nondiseased_kidney', 'D', 'Nondiseased kidney')]:
    obs = pd.read_csv(base / f'{sample}_observed_collective_trajectory.csv')
    nul = pd.read_csv(base / f'{sample}_aggregation_null_envelope.csv')
    uo = next((c for c in obs.columns if c.lower() == 'u' or 'removed_fraction' in c.lower()))
    phi = next((c for c in obs.columns if c.lower() == 'phi' or ('collective' in c.lower() and pd.api.types.is_numeric_dtype(obs[c]))))
    un = next((c for c in nul.columns if c.lower() == 'u' or 'removed_fraction' in c.lower()))
    med = next((c for c in nul.columns if 'median' in c.lower()), None)
    lo = next((c for c in nul.columns if any((x in c.lower() for x in ['q025', 'lower', 'lo_']))), None)
    hi = next((c for c in nul.columns if any((x in c.lower() for x in ['q975', 'upper', 'hi_']))), None)
    if med is None:
        nums = [c for c in nul.columns if c != un and pd.api.types.is_numeric_dtype(nul[c])]
        med = nums[len(nums) // 2]
    fig, ax = plt.subplots(figsize=(4.2, 3.4))
    if lo and hi:
        ax.fill_between(nul[un], nul[lo], nul[hi], alpha=0.18, label='Aggregation-only null')
    ax.plot(nul[un], nul[med], lw=1.2)
    ax.plot(obs[uo], obs[phi], lw=1.8, label='Observed')
    ax.set_xlabel('Removed fraction, u')
    ax.set_ylabel('Collective fraction, Φ(u)')
    pass
    ax.legend(frameon=False, fontsize=7)
    save(fig, f'Fig3{letter}_collective_emergence')
res = Path(a.main_results)
for sample, label in [('healthy_reference', 'Healthy brain'), ('nondiseased_kidney', 'Nondiseased kidney')]:
    cells = pd.read_parquet(res / 'hierarchy_level0_v070' / sample / 'cells.parquet')
    ids = pd.read_csv(base / f'{sample}_M1_peak_event_level0_ids.csv')
    if 'level0_index' not in ids.columns:
        raise RuntimeError(f'{sample}: frozen M1 event table lacks required level0_index column; columns={ids.columns.tolist()}')
    idx = pd.to_numeric(ids['level0_index'], errors='raise').astype(np.int64).to_numpy()
    if idx.size == 0:
        raise RuntimeError(f'{sample}: frozen M1 event has no Level-0 members')
    if idx.min() < 0 or idx.max() >= len(cells):
        raise RuntimeError(f'{sample}: Level-0 indices out of bounds for {len(cells)} cells: [{idx.min()}, {idx.max()}]')
    x = next((c for c in cells.columns if c.lower() in ['x', 'x_centroid', 'centroid_x']))
    y = next((c for c in cells.columns if c.lower() in ['y', 'y_centroid', 'centroid_y']))
    mask = np.zeros(len(cells), dtype=bool)
    mask[idx] = True
    fig, ax = plt.subplots(figsize=(4.2, 4.0))
    ax.scatter(cells[x], cells[y], s=0.3, alpha=0.12, rasterized=True)
    ax.scatter(cells.loc[mask, x], cells.loc[mask, y], s=1.5, alpha=0.85, rasterized=True)
    ax.set_aspect('equal')
    ax.axis('off')
    pass
    save(fig, f'Fig3E_{sample}_spatial_merger')
f = pd.read_csv(base / 'Fig3F_molecular_effects.csv')
print('molecular columns', f.columns.tolist())
samplecol = next((c for c in f.columns if c.lower() in ['sample', 'tissue', 'organ']), None)
genecol = next((c for c in f.columns if 'gene' in c.lower()), f.columns[0])
eff = next((c for c in f.columns if 'effect' in c.lower() or 'delta' in c.lower() or 'log' in c.lower()), None)
if eff:
    groups = f.groupby(samplecol) if samplecol else [('All', f)]
    for lab, g in groups:
        q = g.assign(_abs=g[eff].abs()).nlargest(min(15, len(g)), '_abs').sort_values(eff)
        fig, ax = plt.subplots(figsize=(4.5, 3.8))
        ax.barh(q[genecol].astype(str), q[eff])
        ax.axvline(0, lw=0.7)
        ax.set_xlabel(eff)
        pass
        save(fig, f"Fig3F_{str(lab).replace('/', '_')}_molecular")
(out / 'provenance.json').write_text(json.dumps({'inputs': 'frozen validated Fig3 V3/V3.1 tables + Level0 cells', 'hierarchy_rerun': False}, indent=2))
print('WROTE', out)
