# PANEL-ONLY PRESENTATION COPY — generated by SUTRA_PANEL_ONLY_CANONICAL_V0_2
# Scientific calculations/data access are unchanged; only axes/figure titles and literal panel letters are suppressed.
from pathlib import Path
import numpy as np, pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT = Path.home() / 'Desktop/SUTRA_PAPER_REPRO/relational_information_v052_folds'
OUT = Path.home() / 'Desktop/SUTRA_PAPER_REPRO/supplementary/SuppFig06_Relational_Information_v057'
OUT.mkdir(parents=True, exist_ok=True)
S = pd.read_csv(ROOT / 'information_decomposition_summary.csv')
F = pd.read_csv(ROOT / 'nested_fold_aucs.csv')
D = S[S.analysis.eq('drop_one')].copy()
FD = F[F.analysis.eq('drop_one')].copy()
ORDER = ['organizational_state', 'geometry', 'topology', 'mechanics_communication', 'molecular_distance']
LAB = {'organizational_state': 'Organizational\nstate', 'geometry': 'Geometry', 'topology': 'Topology', 'mechanics_communication': 'Mechanics /\ncommunication', 'molecular_distance': 'Molecular\ndistance'}
SAMPLES = ['healthy_reference', 'alzheimers', 'gbm_reference_addon', 'nondiseased_kidney', 'prcc']
DISP = {'healthy_reference': 'Healthy brain', 'alzheimers': "Alzheimer's disease", 'gbm_reference_addon': 'GBM', 'nondiseased_kidney': 'Nondiseased kidney', 'prcc': 'PRCC'}
BRAIN = SAMPLES[:3]
KIDNEY = SAMPLES[3:]
HS = np.array(sorted(D.horizon.unique()), float)

def fold_stats(sample, family='organizational_state'):
    q = FD[(FD['sample'] == sample) & (FD.family == family)]
    rows = []
    for h in HS:
        z = q[np.isclose(q.horizon, h)].delta_auc.to_numpy(float)
        rows.append((h, np.mean(z), np.std(z, ddof=1) if len(z) > 1 else 0.0))
    return np.asarray(rows)
fig = plt.figure(figsize=(12.6, 9.1), facecolor='white')
axA = fig.add_axes([0.12, 0.575, 0.8, 0.275])
axB = fig.add_axes([0.085, 0.105, 0.395, 0.315])
axC = fig.add_axes([0.575, 0.105, 0.395, 0.315])
M = np.array([[D[(D['sample'] == s) & (D.family == f)].delta_auc.mean() for f in ORDER] for s in SAMPLES])
v = max(abs(M.min()), abs(M.max()))
im = axA.imshow(M, aspect='auto', cmap='coolwarm', vmin=-v, vmax=v, interpolation='none')
axA.set_yticks(range(len(SAMPLES)), [DISP[s] for s in SAMPLES], fontsize=10)
axA.set_xticks(range(len(ORDER)), [LAB[f] for f in ORDER], fontsize=9.5)
axA.tick_params(axis='x', pad=11)
pass
for i in range(M.shape[0]):
    for j in range(M.shape[1]):
        axA.text(j, i, f'{M[i, j]:+.3f}', ha='center', va='center', fontsize=9.5, color='white' if abs(M[i, j]) > 0.011 else 'black')

def mean_curve(ax, group, title, letter):
    for s in group:
        a = fold_stats(s)
        line = ax.plot(a[:, 0], a[:, 1], marker='o', ms=3.5, lw=1.55, label=DISP[s], zorder=4)[0]
        col = line.get_color()
        anchors = np.linspace(0, len(HS) - 1, 4, dtype=int)
        q = FD[(FD['sample'] == s) & (FD.family == 'organizational_state')]
        for idx in anchors:
            h = HS[idx]
            z = q[np.isclose(q.horizon, h)].delta_auc.to_numpy(float)
            if len(z):
                jitter = np.linspace(-0.0022, 0.0022, len(z))
                ax.scatter(np.full(len(z), h) + jitter, z, s=8, color=col, alpha=0.2, edgecolors='none', zorder=2)
    ax.axhline(0, color='black', lw=0.8, zorder=1)
    ax.set_xlim(HS.min(), HS.max())
    ax.set_xlabel('Organizational horizon, Δu', fontsize=9.5, labelpad=5)
    ax.set_ylabel('Held-out ΔAUC on removal', fontsize=9.5, labelpad=6)
    pass
    ax.grid(axis='y', alpha=0.13, lw=0.5)
    ax.legend(frameon=True, facecolor='white', edgecolor='none', framealpha=0.9, fontsize=8, loc='upper right', borderpad=0.35, handlelength=2.0)
mean_curve(axB, BRAIN, 'Brain specimens', 'B')
mean_curve(axC, KIDNEY, 'Kidney specimens', 'C')
fig.text(0.06, 0.965, 'Current organizational state carries the most consistent prospective information', fontsize=15, fontweight='bold', ha='left', va='top')
fig.text(0.06, 0.936, 'Lines are paired spatial-CV means within each specimen; faint points show held-out folds at selected horizons. Δu is hierarchy coordinate, not biological time.', fontsize=9.0, ha='left', va='top')
fig.savefig(OUT / 'SuppFig06_Relational_Information_v057.pdf')
fig.savefig(OUT / 'SuppFig06_Relational_Information_v057.png', dpi=450)
plt.close(fig)
fig = plt.figure(figsize=(12.8, 10.4), facecolor='white')
fig.text(0.07, 0.972, 'Feature-family contributions across organizational horizon', fontsize=14, fontweight='bold', ha='left')
fig.text(0.07, 0.943, 'D   Brain specimens', fontsize=12, fontweight='bold', ha='left')
fig.text(0.55, 0.943, 'E   Kidney specimens', fontsize=12, fontweight='bold', ha='left')
lefts = [0.07, 0.55]
width = 0.39
row_h = 0.135
row_gap = 0.032
top = 0.9
for col, (group, _) in enumerate([(BRAIN, 'Brain'), (KIDNEY, 'Kidney')]):
    for r, fam in enumerate(ORDER):
        bottom = top - (r + 1) * row_h - r * row_gap
        ax = fig.add_axes([lefts[col], bottom, width, row_h])
        for s in group:
            q = FD[(FD['sample'] == s) & (FD.family == fam)]
            rows = []
            for h in HS:
                z = q[np.isclose(q.horizon, h)].delta_auc.to_numpy(float)
                rows.append((h, np.mean(z), np.min(z), np.max(z)))
            a = np.asarray(rows)
            line = ax.plot(a[:, 0], a[:, 1], marker='o', ms=2.5, lw=1.1, label=DISP[s], zorder=3)[0]
            sel = np.arange(len(a)) % 3 == 0
            yerr = np.vstack([a[sel, 1] - a[sel, 2], a[sel, 3] - a[sel, 1]])
            ax.errorbar(a[sel, 0], a[sel, 1], yerr=yerr, fmt='none', ecolor=line.get_color(), elinewidth=0.6, capsize=1.5, alpha=0.32, zorder=2)
        ax.axhline(0, color='black', lw=0.65, zorder=1)
        ax.set_xlim(HS.min(), HS.max())
        ax.grid(axis='y', alpha=0.1, lw=0.45)
        ax.text(0.01, 0.88, LAB[fam].replace('\n', ' '), transform=ax.transAxes, fontsize=8.2, fontweight='bold', va='top', bbox=dict(facecolor='white', edgecolor='none', alpha=0.82, pad=1.5))
        if r < 4:
            ax.tick_params(axis='x', labelbottom=False)
        else:
            ax.set_xlabel('Organizational horizon, Δu', fontsize=9)
        ax.tick_params(labelsize=7.5)
        if r == 0:
            ax.legend(frameon=False, fontsize=7.2, loc='upper right', ncol=1)
fig.text(0.07, 0.025, 'Lines are within-specimen paired spatial-CV means; whiskers show held-out fold range. No tissue-level inferential averaging is used.', fontsize=8.8, ha='left')
fig.savefig(OUT / 'SuppFig06_DE_feature_family_small_multiples_v054.pdf')
fig.savefig(OUT / 'SuppFig06_DE_feature_family_small_multiples_v054.png', dpi=400)
plt.close(fig)
print('WROTE', OUT)
